### ISSUE TITLE
Altitude markings are wrong on tracked ride graphs

### ISSUE THREAD

**Issue by RCTMASTA** [IntelOrca/OpenRCT2#1003]
![scr2](https://cloud.githubusercontent.com/assets/3528342/7041399/cf3b9f5e-dd8d-11e4-9884-98201c9e6c8f.png)

**Comment by Gymnasiast** [comment]
It seems to be unsigned as well: the negative markings show up as a number with five digits.

**Comment by Ruedii** [comment]
This still occurs in OpenRCT2 0.3

Did the patch not make it in, or is there a regression somewhere?

**Comment by Gymnasiast** [comment]
@Ruedii Works for me, both in metric and imperial:

![afbeelding](https://user-images.githubusercontent.com/1478678/92028100-c754f380-ed63-11ea-8fcf-8bcb9549c48a.png)

**Comment by Gymnasiast** [comment]
Oh, wait, did you refer to the underflow? That is still there. I will create a new issue for that.
