### ISSUE TITLE
Heads sticking out of paths

### ISSUE THREAD

**Issue by Garogolun** [IntelOrca/OpenRCT2#1008]
After a bit of playing on Linux there were heads stick out of the footpaths. See: ![heads](https://cloud.githubusercontent.com/assets/366164/7098299/16f90c16-dfdf-11e4-906e-95048c94481d.png)
Savegame: https://dl.dropboxusercontent.com/u/15713772/heads.sv6

**Comment by kevinburke** [comment]
Seems fine to me. :)

On Friday, April 10, 2015, Garogolun <notifications@github.com> wrote:

> After a bit of playing on Linux there were heads stick out of the
> footpaths. See: [image: heads]
> <https://cloud.githubusercontent.com/assets/366164/7098299/16f90c16-dfdf-11e4-906e-95048c94481d.png>
> Savegame: https://dl.dropboxusercontent.com/u/15713772/heads.sv6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntelOrca/OpenRCT2/issues/1008>.
>


-- 

--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by IntelOrca** [comment]
This is an invalidation issue... Can anyone else reproduce?

**Comment by adrian17** [comment]
I get the same effect. Also, the cursor changes to a hand, as if I was hovering over a clickable object (but nothing happens when I click them).

![image](https://cloud.githubusercontent.com/assets/4729533/7101046/718506fe-e042-11e4-816d-049a2755b15c.png)

**Comment by Garogolun** [comment]
It appears to be puke, since handymen are cleaning them up. :stuck_out_tongue: Loading the save on Windows in an MSVC compiled version also yields the glitches here.

**Comment by Gymnasiast** [comment]
They aren't burger boxes (litter) or something like that?

**Comment by duncanspumpkin** [comment]
Its an empty burger box. I'm just not sure why the image is wrong.

**Comment by Garogolun** [comment]
Yup, it's litter. I've never noticed them in the original, but now, being focussed on glitches...
![litter](https://cloud.githubusercontent.com/assets/366164/7121173/d4d4644e-e212-11e4-8bbc-c7f4b48bd8a5.png)
