### ISSUE TITLE
Canceling a patrol area also corrupts others

### ISSUE THREAD

**Issue by Garogolun** [IntelOrca/OpenRCT2#1011]
Steps to reproduce:
1. Hire two handymen.
2. Set a patrol area for both.
3. Remove the area of the first by holding down the footstep button and selecting "Cancel Patrol Area".

In the staff list, the footsteps in front of both will disappear. The patrol area of the second can't be canceled anymore. However, the second one still has a patrol area which you can see by "Set Patrol Area".

**Comment by zsilencer** [comment]
i will work on this one

**Comment by duncanspumpkin** [comment]
Is this still happening after zilencers commit?

**Comment by Gymnasiast** [comment]
The issue seems to be solved now. Tested it in both a new game and in an existing save.
