### ISSUE TITLE
Construction rights buying tool does not highlight square

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1017]
When buying land or construction rights, the square you're hovering over should be highlighted, like this:
![scr61](https://cloud.githubusercontent.com/assets/1478678/7134047/726df2e8-e299-11e4-9535-04ce7ee21530.png)
In OpenRCT2, this works for buying land (as seen above) but not for construction rights:
![scr60](https://cloud.githubusercontent.com/assets/1478678/7134060/848932f8-e299-11e4-88c6-a5b2b8736187.png)

**Comment by duncanspumpkin** [comment]
https://github.com/IntelOrca/OpenRCT2/blob/develop/src/windows/park.c#L812
This line should also check if WIDX_BUY_CONSTRUCTION_RIGHTS thats all that needs to be changed.
