### ISSUE TITLE
Supports not disappearing when they should be

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#1020]
![scr1](https://cloud.githubusercontent.com/assets/3945538/7147063/36b7fa82-e2c6-11e4-9931-7bdee9ce181b.png)
https://www.dropbox.com/s/t0bumu25e8tl0kl/Build%20your%20own%20Six%20Flags%20Park%20-%20Hi.sv6?dl=0

**Comment by Gymnasiast** [comment]
You mean the supports on the Dodgems? Those work as intended.

**Comment by PFCKrutonium** [comment]
The roller coaster support is supposed to pass though the Dodgems?

**Comment by Gymnasiast** [comment]
Yes, it worked that way in RCT1 and RCT2. The support doesn't actually pass through the Dodgems by the way, it's cut off in the same way as when you place a base block underneath.
