### ISSUE TITLE
Footpath in the way

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#1027]
When trying ot place a bench or wastebin (or anythng) on a brown footpath it gives an error: 
![image](https://cloud.githubusercontent.com/assets/3930922/7353087/51f58dfa-ed11-11e4-9cfb-2ddad2591eb0.png)
It does work on a normal concrete footpath.

Saved file: http://www.filedropper.com/rct02-dynamitedunes

Edit: playing a bit more, I see that it only happens on the footpath which was included with the ride I built.
Edit2: It happens with all paths included with all rides (also from doubledrop for example)

**Comment by duncanspumpkin** [comment]
Interesting. Could you check to see if it was introduced by the scenery commit which was the last change? I'll have a look at it tonight hopefully.

**Comment by runelaenen** [comment]
It stopped working from OpenRCT.net, Build A62, Commit Hash 67b5a from https://openrct.net/builds.php
Earlier builds just work fine.
