### ISSUE TITLE
Item Color inaccuracy

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#1034]
http://i.imgur.com/GRcOzTM.jpg

This was reported over on OpenRCT.net -  https://openrct.net/forum/topic/21/Black+item+colors+%5BBug%5D

The colors of the items guests are carrying aren't correct, for example the umbrella in the picture is supposed to be colored different and the hat is actually white instead of black.
See how the hat is actually white in the top right color, and the umbrella can't be black, since I don't sell black umbrella's in the park.

**Comment by duncanspumpkin** [comment]
Hey in future can you ask people to upload a save of any bug they encounter. I think I can probably reproduce this bug quite easily so no need in this instance but it makes it easier for most things.

**Comment by PFCKrutonium** [comment]
Noted, Request will be added.
