### ISSUE TITLE
Windows file dialog not opening correctly

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#1039]
When opening the default file dialog, it opens My Documents instead of the saved games folder. 
Also "Œã´wòà´w " will be as the default file name.

[Screenshot](http://i.imgur.com/Wy5e90d.png)
(I haven't seen this myself but someone said so on Skype)

**Comment by duncanspumpkin** [comment]
The file name is because its just copying a random bit of memory. The location is probably something similar.

**Comment by runelaenen** [comment]
And its supposed to do that? :p

**Comment by duncanspumpkin** [comment]
No but i'm just giving an explanation why it does that.
