### ISSUE TITLE
Game crashes when placing decorations

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#1040]
When placing a decoration (most of the time only when they're larger than 1x1), the game crashes.
Photo: http://gyazo.com/58a259b5100915260ab0ae2bedcb5cea
Placing rides or path works.

Photo with verbose output: http://gyazo.com/6111184407f2715bc042d76f0cb0c58b
When enabling verbose output I can see an error popping up: Can't rename park... Off edge of map. Since I didn't try to rename my park, it sounds like an overflow to me.

It's on this build: https://openrct.net/builds/OpenRCT2-74.zip (2015-05-03 14:41)

**Comment by duncanspumpkin** [comment]
The can't rename part of this bug is just because of a mistake where the title should have been removed so ignore that part for now.
