### ISSUE TITLE
Minimising affects window placement

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1056]
When minimising OpenRCT2 and then restoring it again moves all open windows to a cascaded layout.

I think this might be caused by the window resizing code, since minimising sets the width and height of a program window to 0, if I'm not mistaken.

**Comment by IntelOrca** [comment]
Is this fixed now, or is it a wine issue?

**Comment by trigger-death** [comment]
I think it may be a wine issue. But it should be easy to fix nonetheless. Just need to check if the window is minimized during a resize event.

**Comment by Gymnasiast** [comment]
Fixed by #1113.
