### ISSUE TITLE
Raising water outside the bounds of the map crashes the game

### ISSUE THREAD

**Issue by trigger-death** [IntelOrca/OpenRCT2#1057]
When using the water tool and hovering your selection next to the side of the map so some tiles are out of the map, raising the water will crash the game with a call stack of:
```
game_command_raise_water
sound_play_panned
map_get_surface_element_at
map_element_get_type
```

I've checked and this does not happen with the clear scenery tool or land tool.

**Comment by zsilencer** [comment]
looks like there just needs to be a check in map_get_surface_element_at

**Comment by duncanspumpkin** [comment]
Its been done on purpose to return null. At least now it causes an error rather than silently altering a different tile.
