### ISSUE TITLE
When placing a ride if you use backspace to close the window it leaves the yellow arrow behind.

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#1062]
![scr1](https://cloud.githubusercontent.com/assets/3945538/7624053/d0ddd19e-f9b0-11e4-943f-b6cdda6d9188.png)

If you do something like go to place scenery or path, or another ride, it is reset and disappears.

**Comment by duncanspumpkin** [comment]
Original bug (but it can easily be solved in OpenRCT2). Issue is caused by the tool cancel function being called after window close when it should be called during window close. Easiest fix is to call the tool cancel during window_construction_close.
