### ISSUE TITLE
If the Track Preview "Ghost" leaves the map, OpenRCT2 Crashes.

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#1066]
![screenshot 54](https://cloud.githubusercontent.com/assets/3945538/7637418/bc9169f4-fa3b-11e4-918d-7a121f4fdf49.png)

Happens when the Coaster intersects with the edge of the map, but not always.

Then again it could be an interaction with the entrance.

**Comment by zsilencer** [comment]
same issue thats causing #1057 I think we need to edit the code that uses the new map_get_first_element_at system and check for nulls
