### ISSUE TITLE
Some cheat window toggle buttons look pressed, though they aren't activated.

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1084]
A screenshot says more than 1,000 words:
![scr68](https://cloud.githubusercontent.com/assets/1478678/7671311/2f6e0712-fcca-11e4-8903-f0e094e6f34c.png)

I clicked Force sun and closed the window. When I reopened it, both buttons looked pressed. The buttons still _worked_ as intended, only their display is broken.

@PFCKrutonium also had this issue.

**Comment by PFCKrutonium** [comment]
Can Confirm.

**Comment by ThomasdenH** [comment]
I don't seem to be able to reproduce it.

**Comment by duncanspumpkin** [comment]
Can anyone else reproduce this? Perhaps this can be closed.

**Comment by danidoedel** [comment]
Still happens... open cheat window, go to 'ride cheats' and then go to 'park cheats'

**Comment by ThomasdenH** [comment]
I see. The checkboxes on the 'Ride cheats' tab affect the buttons on the 'Park cheats' tab.
