### ISSUE TITLE
Incorrect win condition embedded in scenario text when creating scenario

### ISSUE THREAD

**Issue by rctdude2** [IntelOrca/OpenRCT2#1089]
![err](https://cloud.githubusercontent.com/assets/8041567/7685123/8018c5aa-fd59-11e4-941c-f60368c8dd1c.png)

This appears in scenarios created with OpenRCT2. The incorrect amount appears in the scenario text in both the original RCT2 and OpenRCT2. Different amounts are displayed depending on how many are required (in the case of the picture, 1,000).
Attempting to load the scenario in OpenRCT2 crashes the game (only sometimes, it worked if I set the requirement to 1,200 peeps, which displayed 173 in the scenario text), while it loads fine in the original. If you create a save game in the original, it loads fine in OpenRCT2.
During the scenario, the correct amount of peeps required is displayed (in both games).

I have included the created scenario and the landscape [here](http://highsense.x10.mx/content/other/stextbug.zip). `Lake Meade.sc6` is the landscape and `rctdude2 - Lake Meade.sc6` is the created scenario.

**Comment by rctdude2** [comment]
I did a bit more testing.
* Number of years appears to remain correct in all cases, but it doesn't affect just peep counts (the bug probably only affects the win condition)
* $50,000 park value at a date became $3, crashed
* The above case also happened with repay loan and get park value (same amounts)
* 2,000 guests in park became 208 guests, crashed
* 4,000 became 160, did not crash
* 5,000 became 136, crashed
* $10,000 monthly income from rides became $16, crashed
* $1,000 monthly income from stalls became $1, crashed
* Have fun crashed the game (it loads just fine in the original)

**Comment by duncanspumpkin** [comment]
@rctdude2 I found the source of the crash and it was only happening after a bit of code that gets called randomly at the start of a scenario. This would explain why it wasn't consistantly happening. Hopefully its all fixed in #1091.
