### ISSUE TITLE
Merry-Go-Round music not properly randomizing

### ISSUE THREAD

**Issue by rctdude2** [IntelOrca/OpenRCT2#1101]
As far as I can tell, Merry-Go-Rounds are stuck playing the same song they start with and don't pick any of the other songs. Disabling and reenabling the ride music changes the song, but it still doesn't pick a different song once that one ends.

**Comment by zsilencer** [comment]
so i tried this and seems like its playing different things all the time

**Comment by rctdude2** [comment]
I made a video of it happening: https://www.youtube.com/watch?v=23pyKQDB_8k

**Comment by duncanspumpkin** [comment]
This happens because its looping the music code. It needs to stop the music after each play through in order to call the part of the function that chooses a different song.

**Comment by zsilencer** [comment]
ok, should be fixed now.  also i put the music lists into the code from the exe so now you can customize which tracks play on merry go round if you wanted to.
