### ISSUE TITLE
Attempting to save a ride design will occasionally fail

### ISSUE THREAD

**Issue by rctdude2** [IntelOrca/OpenRCT2#1102]
Attempting to save ride designs of certain types of rides (Observation Tower, Roto-Drop, Launched Freefall) fails with the error "Ride is too large, contains too many elements, or scenery is too spread out". This happens regardless of saving with scenery or not. Additionally, this does not happen with roller coasters, even if they are very large (8,000+ feet total length) or are being saved with large amounts of scenery.

**Comment by rctdude2** [comment]
I just had this happen with both a Looping roller coaster and a Corkscrew roller coaster, so it doesn't seem to be particularly picky with ride types.

**Comment by duncanspumpkin** [comment]
Can you provide a save and instructions to reproduce on that save that way i can find the bug quicker.

**Comment by rctdude2** [comment]
http://a.uguu.se/dnbpbh_ElectricFields.SV6

Attempt to save either the looping roller coaster, the corkscrew roller coaster or the launched freefall.
