### ISSUE TITLE
Closing a ride's window while in scenery selection mode causes the game to remain in that mode

### ISSUE THREAD

**Issue by rctdude2** [IntelOrca/OpenRCT2#1103]
When saving a ride design with scenery, if you close the window of that ride the game will remain in scenery selection mode. The *only* way to exit is by opening the ride's window and exiting as normal by pressing cancel or saving the design (or restarting the game). Additionally, loading a different scenario (or exiting to the main menu) will cause the game to remain in that mode until you exit it (you can reload the scenario with the ride and exit it as normal, even if you exited the scenario).

**Comment by IntelOrca** [comment]
Similar / same as #483
