### ISSUE TITLE
Speed Settings Display "(undefined string)"

### ISSUE THREAD

**Issue by Tkdriverx** [IntelOrca/OpenRCT2#1106]
Along with the speed settings, a few of the settings also display the same thing.

**Comment by duncanspumpkin** [comment]
Are you using english (UK)? The other languages might not have added the new strings yet. See https://github.com/OpenRCT2/Localisation for the other languages.

**Comment by Tkdriverx** [comment]
I'm using US English.

**Comment by Gymnasiast** [comment]
Normally, the US English and Dutch translations are updated within hours of the original commit. But Localisation gets merged once a day: at 3:00 UTC every night. @Tkdriverx asked his question earlier than that.

Generally, the US English and Dutch translations are put into the game one day after the feature itself. If you want a complete translation all the time, use UK English, or download the appropriate file from Localisation.

**Comment by Tkdriverx** [comment]
Thanks guys.
