### ISSUE TITLE
Decimal and thousands separators not localisable

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1110]
English uses a point for decimals and a comma for thousands. Many other languages do this differently - Dutch uses a comma for decimals and a point for thousands. 
It should, therefore, be localisable.

**Comment by IntelOrca** [comment]
String should be added to the language files like how 'year' was done which represents the digit group separator. This can then be used in the format string functions. This also goes for measurement postfixes.

**Comment by AaronVanGeffen** [comment]
Note that some languages (mostly Asian, to my knowledge) group decimals [differently](https://en.wikipedia.org/wiki/Decimal_mark#Digit_grouping). I know unicode characters are unsupported at the moment, but it does mean that the proposed solution might not suffice in the long run.

**Comment by IntelOrca** [comment]
Yes, and its probably not a good idea to bind it 1:1 with a particular language. So it probably needs to be an option of its own with all the possible ways.
