### ISSUE TITLE
Money is kinda weird

### ISSUE THREAD

**Issue by TBloemink** [IntelOrca/OpenRCT2#1116]
![bug openrct](https://cloud.githubusercontent.com/assets/1117643/7735983/3c590f3e-ff41-11e4-98f8-ecf9cc5eced6.png)

When starting a new game in a six flags park, I get this weird thing with the money display. Cannot be right.

**Comment by TBloemink** [comment]
![bug openrct2](https://cloud.githubusercontent.com/assets/1117643/7736045/9a55336a-ff41-11e4-8a54-d18ec815a9d1.png)

apparently not just money, also visitor amounts

**Comment by duncanspumpkin** [comment]
It will happen to any number with a comma/dot seperator until the language files are updated.

**Comment by TBloemink** [comment]
I was just indeed finding this out. Thank you.
