### ISSUE TITLE
[Feature Idea/Request] Warning window when closing game

### ISSUE THREAD

**Issue by Enzemo** [IntelOrca/OpenRCT2#1118]
Hey,

So I'm sure I'm not the only one to do this, but a warning window to say "Are you sure you want to close the game without saving?" would be hugely appreciated.

Many, many times now I've been working on a park and accidently hit the X in the top left corner, and it's all gone in an instant. I just tested it by using the menu and clicking on "Quit Game" and it also immediately closes regardless of time passed, or rides placed.

I thought that RCT2 already had this feature, but maybe it only turns on after a certain amount of time. If this is the case, an option to have it on permanently would be appreciated

Thanks for your consideration

**Comment by rctdude2** [comment]
It exists, it's just disabled by default. It can be enabled in your config.ini file by setting `confirmation_prompt` to `1`.

It really should be in the options menu in-game.

**Comment by IntelOrca** [comment]
I would say this is a bug, because it asks you if you use the menu to quit.
