### ISSUE TITLE
Hardware display toggle graphical glitch

### ISSUE THREAD

**Issue by JarnoVgr** [IntelOrca/OpenRCT2#1129]
I simply tried to use the new hardware display option and when toggling it this is the result: http://i.imgur.com/EHOgr9W.png

Doing a game restart will fix the problem, but then when switching hardware display off, it does the same again.

Specs: 8.1 x64, openrct2.com b624, dedicated nvidia card with latest drivers.

**Comment by runelaenen** [comment]
Resizing the window also seemed to work here.
