### ISSUE TITLE
Incorrect spacing when using decimal comma

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1133]
![naamloos](https://cloud.githubusercontent.com/assets/1478678/7769089/940fe1da-0081-11e5-98f2-33b3544225d5.png)

The space is not in the dutch.txt file.

**Comment by IntelOrca** [comment]
How do you reproduce this?

This is what it looks like for me:
![image](https://cloud.githubusercontent.com/assets/1482259/7770779/d48742be-0089-11e5-9184-1b75e1df955d.png)

**Comment by JarnoVgr** [comment]
Setting it to Dutch (Nederlands) with Guilders as currency gives a space. But doesn't happen when using Deutsch with Guilders.

**Comment by IntelOrca** [comment]
There is a space in the Dutch file, its at the end. It gets reversed because it calculates the digits backwards, I should probably fix that. Anyway the Dutch string needs fixing in localisation.

**Comment by Gymnasiast** [comment]
The Dutch string in Localisation is now fixed. Must have overlooked that one, since I normally don't leave trailing spaces.
