### ISSUE TITLE
Ride ghost in autosaved park, shows strange error message

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1145]
Apparently the game was autosaved during construction of the Merry-go-round. When reloading it, the ghost was still there.

Tried to build another Merry-go-round over the ghost, this is what happened (pay attention to the error message):

![scr80](https://cloud.githubusercontent.com/assets/1478678/7787640/7e4bcd28-0216-11e5-959a-8781252bca90.png)

Bugged save:
https://www.dropbox.com/s/tbr2fszyrqy9clr/Europa%20-%20Europees%20Cultureel%20Fes.sv6?dl=0

By the way, the ride is in the ride list. Clicking it, opening its construction window and then moving it makes it a 'real' ride.

**Comment by duncanspumpkin** [comment]
Hmm this is going to be a pain to fix. The way the game handles ghost rides is it creates a new ride entry and sets a flag for it in the map elements to say its a ghost. Perhaps autosave should be disabled whilst in construction mode?

**Comment by Gymnasiast** [comment]
Could the game check for ghost statuses at load time and remove those elements? Otherwise it will be disabled all the time when the player is building a large roller coaster, without providing an autosave should things go wrong. (Checking and removing could also fix some dodgy saves.)

**Comment by trigger-death** [comment]
What it could do is check if an autosave was delayed, and the moment the user is not in [construction/ride_place/scenery_place] mode the game will autosave.

**Comment by Gymnasiast** [comment]
As I said, that would lose you an entire RC design if the game crashes during construction.

**Comment by duncanspumpkin** [comment]
hmm its not going to be nice either way.

**Comment by IntelOrca** [comment]
When saving the game, it should shift relevant memory and then do a clean up before writing to it without changing the game memory current being used.

**Comment by Gymnasiast** [comment]
You mean it should simply not save the ghost? That would do. :)
