### ISSUE TITLE
Handyman briefly turns into guest before mowing grass.

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1152]
![scr81](https://cloud.githubusercontent.com/assets/1478678/7822367/45d1ba08-03f5-11e5-936a-f2515771a45e.png)

**Comment by PFCKrutonium** [comment]
lol - Best guest 2015?

**Comment by Patrik356b** [comment]
indeed lol.

On Tue, May 26, 2015 at 11:08 PM, Krutonium <notifications@github.com>
wrote:

> lol - Best guest 2015?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntelOrca/OpenRCT2/issues/1152#issuecomment-105665196>
> .
>



-- 
Best regards; Hexile

**Comment by sjoerddebruin** [comment]
It seems they are also slower mowing and the path finding is different?
