### ISSUE TITLE
Cheat 'Remove litter' doesn't affec litter bins

### ISSUE THREAD

**Issue by danidoedel** [IntelOrca/OpenRCT2#1160]
The litter bins remain full. 
Paths are cleaned correct.

**Comment by duncanspumpkin** [comment]
If someone wants to implement this all you need to do is iterate over every map element if its a path check that it has a rubbish bin (if `g_pathBitSceneryEntries[(map_element->properties.path.additions & 0xF) - 1].path_bit.var_06 & (1 << 0)` and the reset the `map_element->properties.path.addition_status` to `0xFF`.
