### ISSUE TITLE
Park size for huge parks is not shown correct

### ISSUE THREAD

**Issue by danidoedel** [IntelOrca/OpenRCT2#1162]
![2015-05-29 15_14_33-openrct2](https://cloud.githubusercontent.com/assets/10995998/7883398/8bf757fe-0616-11e5-8ac9-51210dd7be10.png)

**Comment by rd3k** [comment]
Do you know what the real park size is?

![screen shot 2015-05-31 at 12 08 47](https://cloud.githubusercontent.com/assets/935762/7901731/ab6fb08a-078e-11e5-8e6e-eef0318f34bf.png) ![screen shot 2015-05-31 at 12 07 05](https://cloud.githubusercontent.com/assets/935762/7901732/ab72a1a0-078e-11e5-8fc1-2b8f7a10f26a.png)

**Comment by danidoedel** [comment]
No, but I can try to figure it out.
185x185 (327,580m²) is the last size which is shown correct. 186x186 is shown as -324,150 m²

**Comment by danidoedel** [comment]
Hmm a 50x50 map has 48x48 tiles... Not sure if I want to count a 256x256 map :D

**Comment by rd3k** [comment]
Ah, fix incoming

**Comment by danidoedel** [comment]
Nice!
And if a 256x256 map has really 256x256 tiles and only one entrance the size would be 645,130 m² 
( ([256-2]²-3)x10m²) )
