### ISSUE TITLE
Searchable object list and save minimizer

### ISSUE THREAD

**Issue by duncanspumpkin** [IntelOrca/OpenRCT2#1176]
From http://www.reddit.com/r/openrct2/comments/37vi1k/suggestions_for_openrct2/

Two suggestions from nedesigns.com:
Search tool for objects (using text to find the object you need)
After you finished building a park, there could be an option to remove unused objects to make the file smaller
"MFG"

**Comment by IntelOrca** [comment]
This should work like OpenTTD's download content browser or multiplayer server list.
