### ISSUE TITLE
Original Bug: Synchronizing dualing coasters crash 

### ISSUE THREAD

**Issue by duncanspumpkin** [IntelOrca/OpenRCT2#1178]
From http://www.reddit.com/r/openrct2/comments/37vm4n/bug_fix_suggestion/

Hello, Every time I play the original game and I have racing/dueling rides, I get the access violation error every time I fail to test and release the rides and have them synchronized (closing rides when synchronized, etc.) - is there any way that glitch could be fixed? That would make life a whole lot easier without causing a crash due to synchronization failure. Thanks.

**Comment by IntelOrca** [comment]
Moved to #1322.
