### ISSUE TITLE
Pre-build script only works with PowerShell 3.0 and above

### ISSUE THREAD

**Issue by KingHual** [IntelOrca/OpenRCT2#1205]
The pre-build PowerShell script makes use of Invoke-WebRequest, which is only available in PowerShell 3.0 and above. Windows 7/SP1 comes with PowerShell 2.0 so you need to update [Windows Management Framework](https://www.microsoft.com/en-us/download/details.aspx?id=40855) to build the project.

**Comment by IntelOrca** [comment]
PowerShell 3.0 is now a prerequisite to building the project on Windows. This is because too many people were having issues with the alternative: using curl and unzip.

**Comment by KingHual** [comment]
I decided to post this as I noticed nowhere in the readme PowerShell 3.0 was listed as a prequisite, so I wasn't sure whether people are aware of this.

**Comment by IntelOrca** [comment]
I will edit the readme soon, its very out of date.
