### ISSUE TITLE
Scenario Editor game crash

### ISSUE THREAD

**Issue by danidoedel** [IntelOrca/OpenRCT2#1211]
Game crashed in Scenario Editor while selecting attractions:

Unhandled exception at 0x5075CA58 (openrct2.dll) in openrct2.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

win 8.1 x64

**Comment by duncanspumpkin** [comment]
can you try reproduce this on the latest build. The build that this effected had a major bug in the inventions window. When you say selecting attractions do you mean the inventions window or the object selection window.

**Comment by danidoedel** [comment]
I can try to, but it just happened and I didn't do anything special. It was in the object selection window.

**Comment by kevjoe** [comment]
Everything works fine here on the latest build, I didn't crash.

**Comment by danidoedel** [comment]
No way to reproduce it now, I think it was fixed somehow. Whatever that was... ;)
I'll close that and if it's happening again I will open a new issue.
