### ISSUE TITLE
Game crashes when taking a screenshot in a non-maximized window

### ISSUE THREAD

**Issue by Mitchykins** [IntelOrca/OpenRCT2#1212]
Basically I select screenshot from the dropdown menu and the game crashes

**Comment by danidoedel** [comment]
Giant screenshot or the normal one?

**Comment by Mitchykins** [comment]
Normal

**Comment by Mitchykins** [comment]
Sort of an update, turns out the game won't crash if the window is maximized, but any other size window, and the game crashes

**Comment by duncanspumpkin** [comment]
I can't reproduce this. Can you give me full steps to reproduce.

**Comment by Mitchykins** [comment]
Basically, try taking a screen shot when the window isn't maximized (restore the game window and resize to something smaller)

It might be on my end, but then again it doesn't crash when it's maximized

**Comment by Mitchykins** [comment]
Seems like the glitch is fixed now

**Comment by zsilencer** [comment]
ive had this happen before as well

**Comment by duncanspumpkin** [comment]
Anyone still able to reproduce this or can it be closed?

**Comment by kevjoe** [comment]
I couldn't reproduce this problem.
