### ISSUE TITLE
Graphical glitch in scenario editor (new)

### ISSUE THREAD

**Issue by danidoedel** [IntelOrca/OpenRCT2#1213]
Similar to #1161 and happens after the fix of #1210 

Select a huge land own tool (e.g. 64), press escape and select 'build park entrance', the land tool size 64 will show up.

**Comment by duncanspumpkin** [comment]
Ah sorry my bad https://github.com/IntelOrca/OpenRCT2/blob/develop/src/windows/map.c#L644-L646
should also check that `RCT2_GLOBAL(RCT2_ADDRESS_TOOL_WIDGETINDEX, uint8) == WIDX_SET_LAND_RIGHTS`
