### ISSUE TITLE
Ride profits are calculated wrong

### ISSUE THREAD

**Issue by danidoedel** [IntelOrca/OpenRCT2#1227]
Ride profits are calculated wrong in some cases. The calculation of 'profit' - 'running cost' is always rounded down. 

For example:
-4.60 is displayed as -4, but should be -5

As a result profit is sometimes displayed as -0
![2015-06-05 01_18_14-openrct2](https://cloud.githubusercontent.com/assets/10995998/7996461/cfa59a6a-0b20-11e5-8693-b060b4d49159.png)![2015-06-05 01_18_22-openrct2](https://cloud.githubusercontent.com/assets/10995998/7996463/d0c942ac-0b20-11e5-938d-53819d2a1cc5.png)

**Comment by Gymnasiast** [comment]
By the way, € -0 would be the correct rounding for Doubledrop in this case. (Roto-Drop 1 should of course be € -1, not € -0)

**Comment by danidoedel** [comment]
Sorry, but Doubledrop is correct :)

**Comment by Gymnasiast** [comment]
No, -0.40 should be rounded to -0, since it's negative.

**Comment by danidoedel** [comment]
There is no negative 0 in ordinary arithmetic...

**Comment by Vijfhoek** [comment]
Pretty sure it's still used for statistics though.

**Comment by Gymnasiast** [comment]
It's frequently used to describe temperatures that are just below 0°C for example. The minus sign is significant, since any profit below 0.0 is a loss (the same way a temperature below 0.0 is freezing.)

**Comment by Vijfhoek** [comment]
Why not just show the decimals by the way?

**Comment by Gymnasiast** [comment]
Good point, actually! I don't know why CS chose to show two rounded and one non-rounded amount.

**Comment by danidoedel** [comment]
No there is no signed zero in that case... sorry to say...
Anyway... it would make more sense to just show the decimals...
