### ISSUE TITLE
"Whizzed"/Failed screenshots at "weird" resolutions

### ISSUE THREAD

**Issue by rctdude2** [IntelOrca/OpenRCT2#1230]
This is a strange one as it seems to be completely random. For what it's worth, I have hardware drawing enabled, so these may be related to that.
I can get these to reproduce whenever I mess with the window size and set it to random resolutions, but again it seems to be completely random so it may or may not occur when you try it.

Happened at a screen size of 1269x400: `ERROR[..\src\interface\screenshot.c:271 (screenshot_dump_png)]: Unable to save screenshot, 1481655576: (null)` I couldn't get this to happen again by manually setting the screen size at that resolution in the config, however it caused a "whizzed" screenshot when I tried after I set it and restarted.

The following happened with hardware drawing enabled, but didn't happen when I disabled it. Screen size of 1120x764.
![scr13](https://cloud.githubusercontent.com/assets/8041567/7998453/1f2a88c8-0b0a-11e5-9969-d16f27879356.png)

**Comment by zsilencer** [comment]
looks like this fixes it
