### ISSUE TITLE
Save dialog using scenario name for (new file) when it should be using the park name

### ISSUE THREAD

**Issue by rctdude2** [IntelOrca/OpenRCT2#1231]
Self explanatory. Original RCT2 used the park name for the save files, while OpenRCT2 is using the scenario name.

**Comment by LRFLEW** [comment]
I'm getting the title as "My new scenario" when I attempt this.

**Comment by rctdude2** [comment]
For the save dialog in a scenario, not the scenario editor. Fixing the save dialog should fix the scenario editor "bug" (it's just using that because it doesn't have a scenario name by default).
