### ISSUE TITLE
Default file name when saving in the scenario editor is incorrect

### ISSUE THREAD

**Issue by LRFLEW** [IntelOrca/OpenRCT2#1245]
Similar in nature to #1231, but turns out to be a separate bug, so I'm reporting it here.

The behavior of the bug is different depending on whether #1244 has been merged. Before the PR, the file will always default to "My new scenario". After the PR, it will default to the default save name of the last scenario played or empty string if there wasn't a game played since starting.

**Comment by rctdude2** [comment]
This isn't affecting just the scenario editor, either. After the PR, the file name does not update when attempting to save a new file from an already saved game.

**Comment by LRFLEW** [comment]
Fixed with #1244
