### ISSUE TITLE
Whizzed title screen screenshots

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1255]
Tried to take a screenshot in the title screen, this is what happened:

![scr84](https://cloud.githubusercontent.com/assets/1478678/8024045/2c2fbbc0-0d25-11e5-9f30-1f83708678f1.png)

Edit: I also get them in-game.

**Comment by AaronVanGeffen** [comment]
Sounds like #1230, which was supposedly fixed with 71ae580?

**Comment by Gymnasiast** [comment]
Apparently it wasn't, or it least not completely. I even made a few good screenshots today before it encountered this bug.

What's even stranger is that it seems to work correctly when I turn Hardware display on.

**Comment by zsilencer** [comment]
sorry didn't test enough, my new pull request should fix everything now.

**Comment by duncanspumpkin** [comment]
Can someone retest this to confirm if its still happening.

**Comment by kevjoe** [comment]
It doesn't seem to happen for me.
