### ISSUE TITLE
Game closing when pressing X on window

### ISSUE THREAD

**Issue by Enzemo** [IntelOrca/OpenRCT2#1264]
Hey,

I recently just X'd out of my game, and I saw the "Save" "Don't Save" menu pop up but the game closed immediately anyway.

I know that at one point this wasn't happening, so thought it best to report the change

Thanks guys, I very much appreciate all the work.

**Comment by Gymnasiast** [comment]
I noticed this yesterday as well.

**Comment by duncanspumpkin** [comment]
Confirmation prompt has been default to 0 for quite a while. We can change the default to 1. I think whats happened is something recently forced a reset on config options.
