### ISSUE TITLE
[Suggestion] slower speed or allow construction in pause mode

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#1268]
I'm a person who can work hours on a single attraction, theming every little bit of a ride that is possible, and I'd like to take my time for that. However, you can't build in the pause mode, and it's often that a year has passed before I even open up my ride, which causes my other rides to break down etc.

It would be cool to be able to build in pause mode, or get a slow or ultra-slow mode in the game, so we can build without looking at the clock.

If this could be added, it would be so awesome :3

Original post: https://openrct.net/forum/topic/56/last/suggestion-slower-speed-or-allow-construction-in-pause-mode

**Comment by kevjoe** [comment]
As the linked suggestion was mine, I really would love this to be in the game. 
If the "build in pause mode" possibilty ain't possible, it could be added as a "slow" option in the game speed menu. 
This can however break several scenario's that are based around time, to give you a challenge to make it in for example 4 years. If you can build everything in pause mode, that would really break the game. So perhaps this should be possible only in sandboxes, or a toggle in either settings or scenario setup?
That's only thinking forward, most of it pointed out by Wil1131 on the linked post, but just having the ability to build in pause would be awesome as of now.

**Comment by Patrik356b** [comment]
Perhaps add this to cheats list?. "Allow building while paused"

**Comment by Gymnasiast** [comment]
Adding a 'build in pause mode' cheat is certainly possible, as the game simply checks whether the game is in pause mode when you try to place something, and shows an error if it is.

**Comment by kevjoe** [comment]
I seriously love you guys. <3

**Comment by Gymnasiast** [comment]
Implemented with #1297.

**Comment by 97-109-107** [comment]
I'm running build 400 and can't build in build mode:
![How it looks like](https://i.imgur.com/7Kf1ygP.png)

I've tried various orders of operation
- running, cheat, pause, try
- paused, cheat, try

Both with the cheat window open and closed.

**Comment by Gymnasiast** [comment]
In the Known issues, which are distributed with the build, it clearly states that building in pause mode doesn't work for all game commands yet: ride building is one of them.

**Comment by IntelOrca** [comment]
It won't be long now before this is possible.

**Comment by 97-109-107** [comment]
@Gymnasiast I'm sorry, didn't know about that document. However I don't see anything like that in the extracted build which I downloaded from https://openrct.net/builds.php
These are all the files in that zip:
````
.
├── curl-ca-bundle.crt
├── Data
│   ├── g2.dat
│   ├── language
│   │   ├── dutch.txt
│   │   ├── english_uk.txt
│   │   ├── english_us.txt
│   │   ├── french.txt
│   │   ├── german.txt
│   │   ├── hungarian.txt
│   │   ├── italian.txt
│   │   ├── polish.txt
│   │   ├── portuguese_br.txt
│   │   ├── spanish_sp.txt
│   │   └── swedish.txt
│   └── title
│       ├── openrct2
│       │   ├── achilleshiel.sv6
│       │   ├── faas.sv6
│       │   ├── mci.sv6
│       │   ├── pfckrutonium1.sv6
│       │   ├── pfckrutonium2.sv6
│       │   ├── poke.sv6
│       │   ├── rid6.sv6
│       │   ├── script.txt
│       │   ├── shotguns.sv6
│       │   └── triggerdeath.sv6
│       └── rct2
│           └── script.txt
├── openrct2.dll
├── openrct2.exe
└── SDL2.dll
````

**Comment by Gymnasiast** [comment]
That's an issue with those builds then, since those from openrct2.com and ursalabs do include it. (The openrct.net builds are a bit rickety.)

Anyway, to get back to your problem, it will be implemented as soon as possible - which means: after we decompiled the responsible functions.
