### ISSUE TITLE
Upper options not modifiable in Fullscreen (desktop) mode

### ISSUE THREAD

**Issue by danidoedel** [IntelOrca/OpenRCT2#1275]
![2015-06-09 17_31_56-openrct2](https://cloud.githubusercontent.com/assets/10995998/8062056/0b8fef7a-0ece-11e5-9baa-6d6557239fd1.png)![2015-06-09 17_32_09-openrct2](https://cloud.githubusercontent.com/assets/10995998/8062054/0b8e6d8a-0ece-11e5-9719-6fe718c19c69.png)![2015-06-09 17_32_20-openrct2](https://cloud.githubusercontent.com/assets/10995998/8062057/0b902508-0ece-11e5-94a0-e05ddcdb52d3.png)![2015-06-09 17_32_32-openrct2](https://cloud.githubusercontent.com/assets/10995998/8062053/0b8c6db4-0ece-11e5-9522-4d7f716dda8a.png)![2015-06-09 17_32_40-openrct2](https://cloud.githubusercontent.com/assets/10995998/8062055/0b8f615e-0ece-11e5-94de-f46c81f1ed09.png)

**Comment by kevjoe** [comment]
I have been able to replicate this, but it only happens in windowed fullscreen. Normal fullscreen works fine.

**Comment by duncanspumpkin** [comment]
Yeah it will be caused by the refactoring that was done the other day. Should have a fix in a giffy.
