### ISSUE TITLE
Look for RCT2 files within OpenRCT2 root

### ISSUE THREAD

**Issue by webhawk** [IntelOrca/OpenRCT2#1305]
I saw in the readme that OpenRCT2 looks for the RCT2 data files in a few directories like the default installation path of the regular RCT2 setup. Would it be possible to allow OpenRCT2 to look in its own directory as well? This way a 'Portable' version is easily made and the folder looks like this!

![rct2 root dir](https://cloud.githubusercontent.com/assets/7838707/8096642/a578b692-0fd9-11e5-8d65-b41ebc569953.png)

Because this is an OpenRCT2 thing I imagine this would relatively easy to do :-)

**Comment by PFCKrutonium** [comment]
On a related note, could it be possible to load files from more than one location? For example, the layout seen here for custom objects, and the original folder for the original files?

**Comment by duncanspumpkin** [comment]
We can't change the custom object locations yet. You are stuck with just one location. It can only be changed when every reference to the object list has been done (basically the whole thing implemented).
