### ISSUE TITLE
Some windows will leak lines from the dropdown

### ISSUE THREAD

**Issue by mzmiric5** [IntelOrca/OpenRCT2#1307]
Kind of hard to explain (hence the pic bellow), but blindirl spotted this on the stream and we were able to recreate. Basically you open 2 windows while in game and u put a window that has a dropdown on the right of the other window (with some spacing between them), then opening and closing the drop down or leaving it open will cause the window colored lines to be rendered. Sometimes it will be just one short one, sometimes more longer ones, sometimes they flicker and sometimes they are static.

![orct2issue](https://cloud.githubusercontent.com/assets/1480072/8097735/05914d56-0fde-11e5-8698-f500659b4596.png)

**Comment by IntelOrca** [comment]
Happens to me without any other windows open.

**Comment by wolfblake** [comment]
I had the same issue but with one window open. 
![scr2](https://cloud.githubusercontent.com/assets/5151086/8265690/8cd14f3a-16ca-11e5-9a65-e227a2748016.png)

**Comment by PFCKrutonium** [comment]
I also recently (~6 hours) experienced this.
