### ISSUE TITLE
Ride selection in scenario editor 

### ISSUE THREAD

**Issue by chrismilne300** [IntelOrca/OpenRCT2#1320]
I've always felt a bit daunted by the huge list of rides in the scenario editor. Wouldn't it be better to categorise them like it does in the actual game. I've done a quick mock up of what I mean to try and better explain it. Note, I haven't bothered to categorise the list, its more to give you an idea of the UI. 
![ride](https://cloud.githubusercontent.com/assets/1381723/8138521/8e9e94f8-1143-11e5-8f73-45d54c815538.png)

**Comment by Gymnasiast** [comment]
We could put them in the filter list, like we do with RCT2/WW/TT/Custom already.

**Comment by IntelOrca** [comment]
I think what is shown in the picture works better from a UX point of view.

**Comment by kevjoe** [comment]
That would indeed be a big improvement!

**Comment by Gymnasiast** [comment]
I would move the search bar above the tabs though, and also allow deselecting all tabs to see everything at once. (Like this: click on the Gentle tab to see all gentle rides, click it again to deselect it and show everything.)

**Comment by Patrik356b** [comment]
Even better would be if we could multi-select ride categories, i.e. while holding shift key you click on several of these and only these categories are shown. Clicking normally would clear multi-select

**Comment by Gymnasiast** [comment]
@Patrick356b: Yeah, that would be even better: normal click: select one; shift/ctrl+click: select one, more or all. OpenTTD has put advanced GUI features under the Ctrl button to cater for power users while keeping the UI simple for everyone.

**Comment by trigger-death** [comment]
Hate to burst everyone's bubble but this may not be possible without slowdowns. I'm pretty sure chunk data isn't loaded unless it's in the current scenario and we need that data to get ride catagories.

**Comment by Gymnasiast** [comment]
@trigger-death : It would be possible if the category data was saved in the object list, I'd imagine.

**Comment by trigger-death** [comment]
I gave it a try but I found the major problem. Objects chunks aren't loaded unless the game is reloading the object cache. So the only way to load the filter data would require that the game take forever to startup every time. This won't be possible until major changes have been implemented to the object system in the future.
