### ISSUE TITLE
Please add a setting to invert right-click scrolling directions

### ISSUE THREAD

**Issue by yayachiken** [IntelOrca/OpenRCT2#1332]
It might be just me, but the movement direction of scrolling (when dragging the mouse while right-clicking) is hard to get used to.

Right now, in RCT2 and OpenRCT2 If you right-click and move the mouse up, the view moves up also.

But most online maps or other games etc. make you "drag" the terrain, so if you "grab" the terrain with your mouse, the mouse pointer will stay on the position where it "grabbed" the terrain, and pull the terrain along with its movement, which naturally causes the view to move in the opposite direction.

While both approaches make sense, I think the "online-map" mode of grabbing and dragging the map has become more common. But veteran RCT2 players probably don't want to break their habits either. So I would request as an enhancement, that an option is added to at least invert the current map scrolling behaviour. For example, our "cousin" OpenTTD also offers this setting.

An even better fix in my opinion would be, if the mouse pointer really moved together with the terrain as it is dragged to make it even more intuitive for the user. But that would probably be more work, so if the pointer stays stationary (if you don't know what I mean, look how OpenTTD handles it, there the pointer stays stationary which feels a bit weird) it would be okay with me as well

Also I hope I did not overlook something in the settings. If the feature I requested already exists, just close this :)

**Comment by ThomasdenH** [comment]
Can be closed.
