### ISSUE TITLE
Title screen scenarios fail to load

### ISSUE THREAD

**Issue by JarnoVgr** [IntelOrca/OpenRCT2#1368]
When using the OpenRCT2.com builds it seems that the ZIP downloads fail to load the title screen scenarios. Even though they're located in the appropriate folder. Installer seems to work fine.

Error: "[ERROR[..\src\scenario.c:187 (scenario_load)]: failed to find scenario file."

Link to build: https://openrct2.com/download/809

**Comment by JarnoVgr** [comment]
I found what's causing this. If the folder containg the exe/dll has dots/periods in it, it fails to load the title sequence.

This doesn't work: 'OpenRCT2-0.0.2-pre-release-b820'
This works fine: 'OpenRCT2-pre-release-b820'

It seems to be caused by a change in this commit: https://github.com/IntelOrca/OpenRCT2/commit/be98d6d85037cdf7ff0567a582bd1c45fc5e00d4

Could a dev look into this?

**Comment by mzmiric5** [comment]
hmm, it would appear that the fullpath resolution is breaking on folders that have dots in names ...., i'll try to find an alternative solution to path resolution
