### ISSUE TITLE
Compatibility with 8cars and other trainers

### ISSUE THREAD

**Issue by Gammadivided** [IntelOrca/OpenRCT2#1371]
Is there any way to make this possible?

**Comment by Gymnasiast** [comment]
No. 8 cars even chokes on the slight differences in RCT2 versions (like the different languages). OpenRCT2 has its own cheats window for this purpose, with many more in the plans.

**Comment by Gammadivided** [comment]
Aww. But, I guess it's okay if there will be more cheats.

**Comment by sjoerddebruin** [comment]
You can always request some cheats that you want.
