### ISSUE TITLE
Long path overflowing in the load/save window

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#1378]
![scr3](https://cloud.githubusercontent.com/assets/1478678/8212245/ee8b1816-151a-11e5-9e37-46f6827a7b28.png)

**Comment by ThomasdenH** [comment]
Can be closed.

**Comment by Gymnasiast** [comment]
If you add "closes #1378" or "fixes #1378" to your PR, it will close it automatically. (Something for next time :-) ).

**Comment by ThomasdenH** [comment]
I see. I knew you could reference them, but this is quite handy. Thanks!
