### ISSUE TITLE
Deleting lamps from queues changes the queue into a path.

### ISSUE THREAD

**Issue by Phasedetect** [IntelOrca/OpenRCT2#1391]
If you misplace a lamp on a queue and have to remove it, the queue tile becomes a regular path tile.

**Comment by sjoerddebruin** [comment]
Can confirm.

**Comment by IntelOrca** [comment]
Was this an original bug?

**Comment by rctdude2** [comment]
It did happen in the original for me, but not all the time.

**Comment by IntelOrca** [comment]
Yeah, I asked because I had to diverge from what the original assembly did to fix this.
