### ISSUE TITLE
Track place scenery ghost does not get removed

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#1396]
**Steps to reproduce:**
1. Open _Roaring Twenties - Prison Island_.
2. Build a new ride, BarnStorming Coaster.
3. Move the placement marker of the Loop-the-Loop coaster around the map.

http://i.imgur.com/Y0XNDdY.jpg

**Comment by MrPker5** [comment]
Once i do the same steps with a self-made coaster of that type, the ghost scenery doesnt stay. So the problem is probably with the Loop-the-Loop

**Comment by IntelOrca** [comment]
@MrPker5 did your self-made track include the same pole scenery that gets stuck?

**Comment by MrPker5** [comment]
maybe i have found the problem, once i disable the scenery that is attched to it (the building) it doesnt happen.
