### ISSUE TITLE
Idea: Construction while paused

### ISSUE THREAD

**Issue by Superjustinbros** [IntelOrca/OpenRCT2#449]
Quote form the TVTropes page:

"The first two games severely limit what the player can do while the game is paused (the player can rename things and tweak the theming of a ride, and that's about it). This doesn't sound so bad until you realize that designing a custom coaster layout involves a lot of trial and error, especially if you want it to make use of the topography. Every second spent tweaking this or that segment of a new coaster is a second the player can't focus on other pressing issues or plunk your handyman down next to the vomit that's been piling up. RollerCoaster Tycoon 3 is the first game in the series that allows the player to do almost any kind of construction or terraforming even when paused."

**Comment by Gymnasiast** [comment]
Has been implemented now.
