### ISSUE TITLE
Quitting via the close icon should show quit game prompt.

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#457]
Currently quitting the game shows a new quit game prompt window which just has the options quit or cancel. It should show the same prompt as when you click quit via the menu with the options, save, don't save and cancel. Just with the outcome of quitting the game rather than quitting to the main menu.

Further to this, I think the save menu should have two quit options. One to quit to main menu and another to quit the game entirely.

**Comment by Gymnasiast** [comment]
Has been implemented in the meantime.
