### ISSUE TITLE
Idea: Ride/Attractions Manager

### ISSUE THREAD

**Issue by Superjustinbros** [IntelOrca/OpenRCT2#464]
Currently when I was surfing for add-on content to add to RCT2, I accidentally added a few duplicate rides/attractions to the game (such as the Balloon Stall and this fan-made "Bull Ride" flat ride). If there could be a way to identify the source .dat file providing the duplicate ride/attraction(s), allowing you to go into the Objdata folder and remove the duplicates, it'd be very useful.

**Comment by Gymnasiast** [comment]
Has been implemented in the meantime, this can be closed.
