### ISSUE TITLE
Being Able to quit a game while in "Select Scenery to save track design with"

### ISSUE THREAD

**Issue by Superjustinbros** [IntelOrca/OpenRCT2#483]
I believe this was a bug in the original RCT2 as well; Basically when you go to save a track design with scenery, then opt to quit the game through the Options menu, you will still be in the "Select Scenery" mode, with all the rides, attractions, and park entrances on the title screen gone, and everything that's there excluding the ground being completely gray.

**Comment by Gymnasiast** [comment]
Fixed with d3587c2.
