### ISSUE TITLE
Paused games have no maps

### ISSUE THREAD

**Issue by AaronVanGeffen** [IntelOrca/OpenRCT2#584]
When trying to navigate a paused game, I noticed paused games do not generate a map. Was this intended? I'm not sure whether this occurs in the original game. 

Regardless, loading a saved game whilst the current game is paused, the new game is loaded paused as well -- which I didn't expect, so it took me a few seconds to realise why no map was showing up.

![](http://i.imgur.com/2GwtTAb.png)

**Comment by Gymnasiast** [comment]
Recently fixed, so this can be closed.
