### ISSUE TITLE
Re-intruduce seeing through water

### ISSUE THREAD

**Issue by AaronVanGeffen** [IntelOrca/OpenRCT2#613]
Something I'm really missing compared to the original RollerCoaster series, is the ability to see through water. Especially in scenarios that consist mostly of water (e.g. Barony Bridge), it's just very hard to see the border of the park without such a feature.

I have no idea how much work it'd entail to re-introduce this, but I'm hoping it can be.

**Comment by Superjustinbros** [comment]
I'd say keep the water the way it is; though perhaps add in an option for more transparent water.

**Comment by AaronVanGeffen** [comment]
The many problems related to water (e.g. invisible scenario borders, staff patrol areas) have been discussed more in depth in #682. Closing this one.
