### ISSUE TITLE
Footpath does not show price in bridge mode

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#642]
This is due to ```_window_footpath_cost``` being used instead of the original memory location and most of the bridge functions not yet implemented.

**Comment by duncanspumpkin** [comment]
What do you mean by does not show price? When I try it out with the latest build I have a price http://i.imgur.com/Ok09RnX.png

**Comment by IntelOrca** [comment]
Oh, I guess I must have fixed this when I was writing more of the footpath code.
