### ISSUE TITLE
Bobsled coaster and research window crash

### ISSUE THREAD

**Issue by Kyben** [IntelOrca/OpenRCT2#658]
Just thought I'd bring up 2 crashes I ran into while playing the latest develop build. The first time was clicking on the research tab in the ride construction window. The second time was clicking the test ride button for the bobsled roller coaster. I'm not sure why, but I can't reproduce these exactly again. May possibly be by clicking any button at the wrong time?

Running Windows 7 64-bit.

**Comment by Gymnasiast** [comment]
In the five months that have passed OpenRCT2 has changed so much, this issue is likely to be gone.
