### ISSUE TITLE
On-ride photos sold counter always stays zero

### ISSUE THREAD

**Issue by mrtnptrs** [IntelOrca/OpenRCT2#670]
Even after a guest sais he find the on-ride photo of a ride amazing, the number of sold on-ride photos at the ride info screen stays zero and doesn't increase. If you need more info, just ask... :) So, the counter of the on-ride photos that are sold, always stays 0.

**Comment by AaronVanGeffen** [comment]
I believe I've noticed something similar recently with an Information Kiosk — one that definitely sold maps, but the map sale count stayed at zero. Might be related.

**Comment by mrtnptrs** [comment]
I can't reproduce this bug at the Information Kiosk with the sold maps counter. Fore me it just increases every time someone buys a map. @AaronVanGeffen Are you sure you can still reproduce this?

**Comment by duncanspumpkin** [comment]
Issue was caused by the primary item count being displayed in the secondary count field. Since information kiosks sell two items you might not have noticed it was incorrect.

**Comment by Gymnasiast** [comment]
I was gonna say just that, you beat me by one minute! (And a fix, which is much more important.)
