### ISSUE TITLE
Balloon only moves sometimes instead of popping when you click on it

### ISSUE THREAD

**Issue by mrtnptrs** [IntelOrca/OpenRCT2#675]
If a guest looses a balloon and you click on it, sometimes the balloon then just moves a tiny bit to the left or right. I tried it many times and reproduced it a few times, but I can't seem to find the exact way to reproduce it. 

It mostly happens for me if a balloon is near a rollercoaster and almost as hight as that one, but it could also be something else of course that triggers this bug.

This happens in OpenRCT2, but also in vanilla RCT2, so you can add the Original bug label to this one.

**Comment by runelaenen** [comment]
"It's not a bug; it's a feature!"

**Comment by mrtnptrs** [comment]
Ok, but I found it sometimes a bit irritating.... Well, it's just how you look at it. What do you think @IntelOrca ?

**Comment by IntelOrca** [comment]
I think this is very low priority for attention at the moment.

**Comment by PFCKrutonium** [comment]
Just throwing my thoughts in here - at a later date this activity should be made toggleable.

**Comment by Leftie76** [comment]
Really not seeing why this is of any concern to anyone lol, its deffo intentional behaviour!

**Comment by Wopian** [comment]
I've always thought this was an easter egg in RCT1/2, pretty sure it is too.

**Comment by IntelOrca** [comment]
I can confirm that this is an intended feature in the game.
