### ISSUE TITLE
Bug: Issues with the RC Designer

### ISSUE THREAD

**Issue by ipatix** [IntelOrca/OpenRCT2#684]
So, I was playing around in the RollerCoaster Designer and discovered upon closing the designer you are asked to save the game.
This is not necessarily a bad thing but upon loading this save the game doesn't load the RC Designer. It will look like a regular empty park with all the rollercoasters you've built but it everything looks like a  regular scenario. Opening various menus as the scenery building menu will crash the game.

**Comment by ipatix** [comment]
Sorry, for that, freaking Firefox won't lemme click the Edit buttons...
Anyway, I just though this problem falls into same category as this:
https://github.com/IntelOrca/OpenRCT2/issues/596

**Comment by duncanspumpkin** [comment]
Its sounds a bit different to #596. I think it rightly should be fixed add a little check to disable saving in RC Designer.

**Comment by Gymnasiast** [comment]
Has been fixed in the meantime, so this can be closed.
