### ISSUE TITLE
Dragging and dropping guests and employees makes them fall through the ground

### ISSUE THREAD

**Issue by ipatix** [IntelOrca/OpenRCT2#685]
Another thing I've noticed is that in the recent OpenRCT2 builds dragging guests/employees (even upon hiring) to everything but paths makes them fall through the ground and cause them to die/disappear.

**Comment by pizza2004** [comment]
On this note, I'm not sure if this is fixed, but when I tried playing with the master branch version it would crash every time I hired a staff member and then tried to click something else without placing them first, like the tab to assign them different jobs.  Or something like this.  It was very frustrating.

**Comment by IntelOrca** [comment]
@pizza2004 I think this was fixed, previously reported in #621. Make sure you run the develop branch which is contains latest updates.

**Comment by pizza2004** [comment]
Yeah, the problem I mentioned is fixed in the latest development build.  As far as the bug ipatix mentions, I see no sign of it in the current development build myself.

**Comment by ipatix** [comment]
Oh, I'm sorry I thought I had an up to date version, problem fixed ;)

**Comment by AaronVanGeffen** [comment]
The problem mentioned by @pizza2004 has been fixed, but the bug with the guests as mentioned by @ipatix is still happening in c5544b52f1e5e62160430167257a50aa33f6cbbc.

**Comment by IntelOrca** [comment]
@AaronVanGeffen I can't replicate it, they always land on the tile for me.

**Comment by AaronVanGeffen** [comment]
@IntelOrca Perhaps it depends on the type of land? I can replicate it consistently in the Grand Canyon scenario.

**Comment by ipatix** [comment]
I just checked it and indeed it does!
I only tried it with Handymen but they seem to fall through clay, sand (the darker one) and all those kinds of colored tiles (not through the regular checkerboard).
