### ISSUE TITLE
When Setting Patrol Area Already Set Patrol Areas Don't Properly Render

### ISSUE THREAD

**Issue by pizza2004** [IntelOrca/OpenRCT2#686]
I hire a handyman, place him, give him a patrol area, hire another handyman, place him, click the set patrol button and the patrol area of the first handyman shows up very slowly and is kind of spotty until I click the area with my button to set the second handyman to have that patrol area, then if I click to turn it off it stays there gray like it's supposed to look.

**Comment by duncanspumpkin** [comment]
Sounds like there is a mistake with invalidating the screen to force a redraw.

**Comment by Gymnasiast** [comment]
Seems to be solved by #1011.
