### ISSUE TITLE
Unable to open SC4 or SV4 Files

### ISSUE THREAD

**Issue by pizza2004** [IntelOrca/OpenRCT2#687]
Despite seeing the code to do so, and a note somewhere that it's possible, when I attempt to load one of these files I can't select it from the load dialog.  I wonder how you were able to test that it was programmed correctly.  Am I just missing something?

**Comment by pizza2004** [comment]
To add to this, whenever I try to open a scenario from a .sc4 file using the command line the game just crashes without starting up at all.

**Comment by IntelOrca** [comment]
RCT1 scenarios and saved games can only be currently loaded from within the scenario editor as a landscape. As for the command line, that should work. Try adding the --verbose flag to the command line and paste your stdout.

**Comment by pizza2004** [comment]
C:\OpenRCT2>openrct2 edit ./forest_frontiers.sc4 --verbose
Starting OpenRCT2 v0.0.1
  Windows (x86)
  Jan  5 2015 21:22:16

Time: 2015/01/12 18:39:20
VERBOSE: initialising game
VERBOSE: loading object list cache (plugin.dat)
VERBOSE: loading scenario details, c:\rct2\Scenarios\Africa - African Diamond Mi
ne.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Africa - Oasis.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Africa - Victoria Falls.SC6

VERBOSE: loading scenario details, c:\rct2\Scenarios\Alpine Adventures.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Amity Airfield.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Antarctic - Ecological Salv
age.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Asia - Great Wall of China
Tourism Enhancement.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Asia - Japanese Coastal Rec
laim.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Asia - Maharaja Palace.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Australasia - Ayers Rock.SC
6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Australasia - Fun at the Be
ach.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Botany Breakers.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Build your own Six Flags Be
lgium.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Build your own Six Flags Gr
eat Adventure.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Build your own Six Flags Ho
lland.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Build your own Six Flags Ma
gic Mountain.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Build your own Six Flags ov
er Texas.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Build your own Six Flags Pa
rk.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Bumbly Bazaar.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Crazy Castle.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Dark Age - Castle.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Dark Age - Robin Hood.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Dusty Greens.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Electric Fields.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Europe - European Cultural
Festival.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Europe - Renovation.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Extreme Heights.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Factory Capers.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Fungus Woods.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Future - First Encounters.S
C6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Future - Future World.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Ghost Town.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Gravity Gardens.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Infernal Views.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Lucky Lake.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Mythological - Animatronic
Film Set.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Mythological - Cradle of Ci
vilization.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\N America - Extreme Hawaiia
n Island.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\North America - Grand Canyo
n.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\North America - Rollercoast
er Heaven.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Prehistoric - After the Ast
eroid.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Prehistoric - Jurassic Safa
ri.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Prehistoric - Stone Age.SC6

VERBOSE: loading scenario details, c:\rct2\Scenarios\Rainbow Summit.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Roaring Twenties - Prison I
sland.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Roaring Twenties - Schneide
r Cup.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Roaring Twenties - Skyscrap
ers.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Rock 'n' Roll - Flower Powe
r.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Rock 'n' Roll - Rock 'n' Ro
ll.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Six Flags Belgium.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Six Flags Great Adventure.S
C6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Six Flags Holland.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Six Flags Magic Mountain.SC
6
VERBOSE: loading scenario details, c:\rct2\Scenarios\Six Flags over Texas.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\South America - Inca Lost C
ity.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\South America - Rain Forest
 Plateau.SC6
VERBOSE: loading scenario details, c:\rct2\Scenarios\South America - Rio Carniva
l.SC6
VERBOSE: loading g1 graphics
VERBOSE: loading scenario, c:\rct2\Scenarios\Six Flags Magic Mountain.SC6
VERBOSE: loading required objects

**Comment by pizza2004** [comment]
This is what happens, and when I try to load them from the scenario editor I can't because the popup that appears has RollerCoaster Tycoon 2 files as the kind of files you can select to load.

**Comment by IntelOrca** [comment]
@pizza2004 You need to actually replace ./forest_frontiers.sc4 with the actual relative or absolute path of the RCT1 scenario or saved game you want to load. That assumes you have a file named forest_frontiers.sc4 in the same directory as openrct2.

I will add the file extensions to the open file dialog. But you can still bypass that by going into the directory containing the file you want to load and typing the first letter of the file name in the file name box on the open file dialog. This will give you an auto complete. Alternative you can type / paste the absolute path to the file in the box.

**Comment by pizza2004** [comment]
I put the file in the same folder as OpenRCT2 and used that.  I tried it with the original name, and then renamed it that because it wasn't working.  I'll try what you said in a minute.

**Comment by pizza2004** [comment]
I just tried opening the file from within the game using the method you suggested of typing in the first letter and using autocomplete and it once again crashed the game.

**Comment by IntelOrca** [comment]
Can you upload the file you are trying to open.

**Comment by pizza2004** [comment]
I've tried with a few different files, but sure, I'll see what I can do.  I'm just grabbing scenarios directly out of the scenarios folder of RCT.

**Comment by pizza2004** [comment]
Alright, here's a link to the file I've been trying to open.  Originally named sc0.sc4 from the RCT scenarios folder: https://www.mediafire.com/?4yxvpullwtxcsby

**Comment by IntelOrca** [comment]
Okay thanks, I think the problem is that RCT1 scenarios and saved gamed can not be opened. However the RCT1 expansion packs (AA/CF and LL) scenarios and saved games can be opened.

**Comment by pizza2004** [comment]
Ah, perhaps that's the problem.  I didn't try with the expansion packs because I didn't realize there would be a difference.

**Comment by IntelOrca** [comment]
I will look into the problem soon.

**Comment by IntelOrca** [comment]
Can some check whether @pizza2004's uploaded park works in vanilla RCT2?
