### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by kaudy** [IntelOrca/OpenRCT2#689]
I'm working on the translation for Brazilian Portuguese. I created this issue to discuss about the terms used in the translation.

-The Translation is currently 40%
-All Translations with "*" must be re-calibrated.

----------------------------------------------------------------------------------------------------------------------------------
Estou trabalhando na tradução para o português brasileiro. Eu criei esse tópico para discutirmos sobre os termos usados na tradução.    

-A tradução está atualmente em 40%
-Todas as traduções com "*" precisam ser novamente verificadas.

**Comment by duncanspumpkin** [comment]
For most of the other translations people have just created a new pull request and put a note saying not ready for merging. That way everyone can look at what you currently have and contribute changes/discuss.

**Comment by kaudy** [comment]
tks, @duncanspumpkin, i will create a new pull request for this translation
