### ISSUE TITLE
Ride open/test/close button is cropped at screen border

### ISSUE THREAD

**Issue by RollingStar** [IntelOrca/OpenRCT2#690]
http://i.imgur.com/LN7kKWt.png

I started the game in fullscreen (1600x900) but it persists even when in windowed 640x480 mode or fullscreen desktop mode.

Could it be that ORCT2-windowed is not the same as RCT2-windowed? I notice that the game's internal resolution is set quite high in ORCT2 - so maybe whatever function checks the screen borders cannot detect a problem.

**Comment by pizza2004** [comment]
I too have noticed this issue, but I just assumed it happened in the original RCT2 as well.  Perhaps there's an issue with part of the game that was recoded?

**Comment by duncanspumpkin** [comment]
The internal resolution is actually correct but its just never displayed (if it was wrong a lot more issues would occur). The one in the options window hasn't been related to the actual resolution for quite some time. The positioning code was never implemented for the text dropdown window for some unknown reason. It is implemented in the image drop down window (colour picker for example). Either way a fix is up for this, thanks for spotting the issue. And no sadly not realted to #691.
