### ISSUE TITLE
Popups are not moved when changing resolution

### ISSUE THREAD

**Issue by RollingStar** [IntelOrca/OpenRCT2#691]
http://i.imgur.com/G7PZK9O.png

http://i.imgur.com/ybJt25H.jpg

When in windowed mode, shrinking the game window does not bring the popups to within the viewport if they are to the right of the new viewport. The "Asdf" popup is still open even in 640x480 windowed, but the popup isn't visible unless you resize the game window. May be similar to #690.

In regular RCT2, the game brings the popup within the viewport when changing resolution.

http://i.imgur.com/QcApd6u.png

http://i.imgur.com/TNFRiwe.png

I closed the options menu in the last screenshot but it was positioned over the Asdf popup, just slightly below it. (The Asdf title bar was still visible.)

**Comment by duncanspumpkin** [comment]
This issue is caused by a missing function call to 6ed710 when the window resizes. I will code up a fix shortly. Thanks again for the bug report.
