### ISSUE TITLE
Intro sequence crashes

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#693]
Intro sequence can be started by command line:
```./openrct2 intro```

Problem with **gfx_transpose_palette**.

**Comment by duncanspumpkin** [comment]
I have a fix in https://github.com/duncanspumpkin/OpenRCT2/tree/fix_intro but need to confirm that the removal of the LocalFree is okay as it would crash my game without it.

**Comment by IntelOrca** [comment]
I think it should be calling **GlobalFree** rather than **LocalFree**, seeing as it calls **GlobalAlloc** in **CommandLineToArgvA**.

According to MSDN:
```
To free the memory, use the GlobalFree function. It is not safe to free memory allocated with GlobalAlloc using LocalFree.
```

**Comment by duncanspumpkin** [comment]
Okay I found the issue arg parse is accessing memory it shouldn't and that is breaking the free.
