### ISSUE TITLE
Numpad keys are recognized but listed as incorrect letters

### ISSUE THREAD

**Issue by RollingStar** [IntelOrca/OpenRCT2#694]
http://i.imgur.com/Vk2fjUQ.png

Numpad keys are recognized and usable, but they are listed in-game as something else. Pressing KP_+ works but the game thinks it's "W". Other keys show up as V or ??? for example. The other V in the screenshot is the real V key. They can coexist just fine with the numpad keys.

**Comment by Gymnasiast** [comment]
I think this is related to #512.

**Comment by RollingStar** [comment]
Yes, this is a dupe of #512.
