### ISSUE TITLE
Tram car type can be changed to Miniature Railway cars, which shouldn't be possible

### ISSUE THREAD

**Issue by RollingStar** [IntelOrca/OpenRCT2#696]
![image](https://cloud.githubusercontent.com/assets/4810902/5789726/8e33e5bc-9e44-11e4-9645-afe8d4e889d4.png)

Trams are unlocked on [this workbench](http://www.nedesigns.com/park/2573/xtreme97-workbench-2012/download/).

edit: The real problem is that this is possible at all. (Thanks, Gymnasiast.)
Expert Parks - Rainbow Summit has Trams and Mini Railway unlocked for easy testing.

**Comment by Gymnasiast** [comment]
Trams and Miniature Railway have the same track type (both IRL and in RCT2). But if you build a Trams ride, you should not see the Steam Trains with Covered Cars, since they're different ride types (which is why they show up separately in the New Ride window)
Does the Miniature Railway ride in this workbench only have Steam Trains with Covered Cars, by any chance (i.e. no other steam trains)?

**Comment by RollingStar** [comment]
![image](https://cloud.githubusercontent.com/assets/4810902/5789844/2ac44bd4-9e49-11e4-99fc-48aa6c730e97.png)

Mini Railway never lets the user switch to Tram type, not even once.

**Comment by Gymnasiast** [comment]
That's correct, because it shouldn't. The problem is that the Trams ride should only offer the vehicle type 'Tram', which it doesn't for same reason.

**Comment by Gymnasiast** [comment]
Six Flags Magic Mountain has Trams unlocked (and built) by default.

**Comment by RollingStar** [comment]
The bug exists on Expert Parks - Rainbow Summit.

![image](https://cloud.githubusercontent.com/assets/4810902/5789868/c3e74b76-9e4a-11e4-8082-0f0b6de9be14.png)

**Comment by RollingStar** [comment]
In regular RCT2, Trams cannot be changed but Mini Railways have a menu (even though there's nothing to change to).

![image](https://cloud.githubusercontent.com/assets/4810902/5789928/6dab6748-9e4e-11e4-96de-38e893ce7e54.png)

**Comment by Gymnasiast** [comment]
This bug also seems to be affecting all other ride types which share track types (and that's quite a few).
Monster trucks is an example.
