### ISSUE TITLE
Cannot open the damn exe

### ISSUE THREAD

**Issue by pGore33p** [IntelOrca/OpenRCT2#702]
So I want to try the OpenRCT and I am pretty noob at setting things up (or things that are new to me) and it just crashed when I try oto open the exe file. I chose the right directory (not the C:/, it is in a USB flash) and jnothing. I tried fiddlling the settings, nope. I tried running it on a command propmpt, nothing.  Is there any help at all here? Thanks. I am using win 8 btw

Will

**Comment by runelaenen** [comment]
Important: Do you have the original game installed?

**Comment by kevinburke** [comment]
When you say "nothing" what do you mean? Is there an error message? A
warning dialog? A stack trace?


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by pGore33p** [comment]
I mean it crashes and yes I have original game installed, the gog version

**Comment by AaronVanGeffen** [comment]
Are you using one of the automated builds? (If you just download a zip from GitHub, you will need to build the game yourself first — you can't just open the executable file in the repository.)

**Comment by pGore33p** [comment]
I extracted it to a directory (not where is rct2.exe) and setted up there, then i setted the directory (it asked me) and then it iopened up a window and then crashed

**Comment by AaronVanGeffen** [comment]
You haven't answered my question, so let me ask it in a different way: do you have an openrct2.dll in the same folder as openrct2.exe?

**Comment by pGore33p** [comment]
Oh thanks for pointing that out! I forgot it! Thanks so much

**Comment by AaronVanGeffen** [comment]
You do not need to run the executable with administrative rights.

Regardless, it is going to be difficult to advice without more information. Does an OpenRCT2 folder exist in your Documents directory? If it does, at least the executable is doing something prior to crashing.

**Comment by IntelOrca** [comment]
Try opening command prompt and executing the OpenRCT2 executable with the command line ```--verbose```. You should get some output that you can send to us for more information.

**Comment by pGore33p** [comment]
@AaronVanGeffen Yeah there exist one and there's a config.ini and plugin.dat...
@IntelOrca I am noob at command prompt therefore I don't know how to execute through it, it just says -- is not recognized as an internal or external command, operable program or batch file. Just saying I don't know anything about command prompt!!

I am 13 btw

**Comment by adrian17** [comment]
Go to the directory where you extracted it:

![image](https://cloud.githubusercontent.com/assets/4729533/5841988/90851920-a1a1-11e4-889f-3a6f336d172c.png)

Hold shift and right-click on empty space. In the context menu, click "open commang prompt here".

Then write this (after the `>`):

![image](https://cloud.githubusercontent.com/assets/4729533/5842022/ca3ef7ee-a1a1-11e4-8a9f-7edf199ea6ea.png)

The game should start and text will appear in the command prompt; wait until it crashes, then  a screenshot of whatever was written in the command prompt and send it here.

**Comment by pGore33p** [comment]
Hmm nothing special to see here... you want it, you got it anyway
![bez nazvu2](https://cloud.githubusercontent.com/assets/10586092/5857279/aa6ebab8-a24a-11e4-9cf5-70f63d487d8d.png)

**Comment by atmaxinger** [comment]
Could be the special chars in your directory names.

**Comment by pGore33p** [comment]
So I have to move it? Duh.

**Comment by IntelOrca** [comment]
Seems to have loaded all those files okay, despite the unicode characters. I guess you try to place everything in C:\openrct2 just in case...

**Comment by pGore33p** [comment]
I'll try it later and see what happens.

**Comment by pGore33p** [comment]
It doesn't work... dammit

**Comment by kevinburke** [comment]
Can you elaborate on "doesn't work"... ? It's very hard to know what code
changes to make based on a statement like that.

Do you get a stacktrace? Do you get an error message? Did the game start
and then crash when you tried to load a level?  What do you expect to see
and what actually happens?


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by pGore33p** [comment]
Oh bugger no it's the same error message that it stopped working and needs to be closed, that generic Windows message when usually an executable crashes. So that are not the directory names.

**Comment by pGore33p** [comment]
@IntelOrca It still doesn't work D:
![bez nazvu](https://cloud.githubusercontent.com/assets/10586092/6046145/d126531e-ac9f-11e4-9fa0-bbda2bf9f236.png)

**Comment by IntelOrca** [comment]
@pGore33p I didn't change anything to fix it because I still don't know what the problem is. This however does now tell us that the game loaded successfully and is crashing with in the main game loop.

**Comment by pGore33p** [comment]
Oh goodie finally...

**Comment by IntelOrca** [comment]
I think it is going be difficult to find the problem without you using a debugger to find the address it is crashing at. It isn't a straight forward task, but you seem to be the only person that has reported an issue of this kind.

If you would like to try and help find out where it is crashing, you can download a debugger such as this:
http://x64dbg.com
Use the 32-bit version and debug openrct2.exe, provide as much information as you can, logs, screenshots etc.

**Comment by pGore33p** [comment]
Well let's see I'll try to debug it.

**Comment by IntelOrca** [comment]
When you begin debuggin it, it might break (due to exception in some OS libraries) a couple of times before the actual bug. Just keep running it until it will run no more.

**Comment by pGore33p** [comment]
@IntelOrca Ok what exactly I have supposed to do? I have no idea what to do in this program, first it says "Paused: System Breakpoint Reached" and in some bar it says "return.ntdll.773D39EF from ntdll.773FE654" what does it mean?

**Comment by IntelOrca** [comment]
You look like you are doing the right thing... just ignore the things related to ntdll.dll Until you get something that says openrct2.

**Comment by pGore33p** [comment]
@IntelOrca Also I am using 64 bit system, so no it said I have to run 64 because "it doesn't support 32 bit" ugh

**Comment by IntelOrca** [comment]
Interesting, it said I had to run the 32 bit version because the application was 32 bit.

**Comment by pGore33p** [comment]
Sorry I edit the post I meant it's opposite

**Comment by pGore33p** [comment]
I am seeing to be lost in the program, when I try to debug it, it does nothing. I tried every single option under the tab and it does NOT work, nothing happens.

**Comment by IntelOrca** [comment]
What does you log say?

**Comment by pGore33p** [comment]
Umm what log? Also, it does say "INT3 breakpoint at 006f08e7"

**Comment by IntelOrca** [comment]
There is a log tab.

**Comment by pGore33p** [comment]
Yeah i know what you mean... I realized there's a tab in log, this says:


Process Started: 00400000 C:\Users\Vítězslav\Downloads\OpenRCT\openrct2.exe
Database file: C:\Users\VTZSLA~1\AppData\Local\Temp\Rar$EXa0.865\x32\db\openrct2.exe.dd32
breakpoint at 006F08E7 set!
DLL Loaded: 77350000 C:\Windows\SysWOW64\ntdll.dll
DLL Unloaded: 00170000 
DLL Unloaded: 74D70000 
DLL Unloaded: 00170000 
DLL Unloaded: 00170000 
DLL Loaded: 74D70000 C:\Windows\SysWOW64\kernel32.dll
DLL Loaded: 752D0000 C:\Windows\SysWOW64\KernelBase.dll
DLL Loaded: 71EB0000 C:\Windows\SysWOW64\winmm.dll
DLL Loaded: 6C2E0000 C:\Windows\SysWOW64\ddraw.dll
DLL Loaded: 75130000 C:\Windows\SysWOW64\user32.dll
DLL Loaded: 76980000 C:\Windows\SysWOW64\gdi32.dll
DLL Loaded: 76A90000 C:\Windows\SysWOW64\comdlg32.dll
DLL Loaded: 76570000 C:\Windows\SysWOW64\advapi32.dll
DLL Loaded: 753A0000 C:\Windows\SysWOW64\shell32.dll
DLL Loaded: 6C410000 C:\Windows\SysWOW64\dinput.dll
DLL Loaded: 6C2A0000 C:\Windows\SysWOW64\dplayx.dll
DLL Loaded: 5C4D0000 C:\Windows\SysWOW64\dsound.dll
DLL Loaded: 6C170000 C:\Users\Vítězslav\Downloads\OpenRCT\openrct2.dll
DLL Loaded: 71E90000 C:\Windows\SysWOW64\winmmbase.dll
DLL Loaded: 75060000 C:\Windows\SysWOW64\msvcrt.dll
DLL Loaded: 6F7F0000 C:\Windows\SysWOW64\dciman32.dll
DLL Loaded: 767D0000 C:\Windows\SysWOW64\shlwapi.dll
DLL Loaded: 765F0000 C:\Windows\SysWOW64\comctl32.dll
DLL Loaded: 77240000 C:\Windows\SysWOW64\sechost.dll
DLL Loaded: 768D0000 C:\Windows\SysWOW64\rpcrt4.dll
DLL Loaded: 76B20000 C:\Windows\SysWOW64\combase.dll
DLL Loaded: 77130000 C:\Windows\SysWOW64\ole32.dll
DLL Loaded: 716E0000 C:\Windows\SysWOW64\powrprof.dll
DLL Loaded: 6C740000 C:\Users\Vítězslav\Downloads\OpenRCT\SDL2.dll
DLL Loaded: 75280000 C:\Windows\SysWOW64\cfgmgr32.dll
DLL Loaded: 74C30000 C:\Windows\SysWOW64\devobj.dll
DLL Loaded: 74D50000 C:\Windows\SysWOW64\sspicli.dll
DLL Loaded: 74F10000 C:\Windows\SysWOW64\imm32.dll
DLL Loaded: 77090000 C:\Windows\SysWOW64\oleaut32.dll
DLL Loaded: 74050000 C:\Windows\SysWOW64\version.dll
DLL Loaded: 72650000 C:\Windows\SysWOW64\SHCore.dll
DLL Loaded: 74D40000 C:\Windows\SysWOW64\cryptbase.dll
DLL Loaded: 74F60000 C:\Windows\SysWOW64\msctf.dll
DLL Loaded: 74CE0000 C:\Windows\SysWOW64\bcryptprimitives.dll
system breakpoint reached!
DLL Loaded: 71E10000 C:\Program Files (x86)\AVG\AVG2015\avghookx.dll
INT3 breakpoint "entry breakpoint" at 006F08E7!
breakpoint at 006F08E7 set!
INT3 breakpoint at 006F08E7!

**Comment by IntelOrca** [comment]
Does it do anything when you now do Debug -> Run (F9)?

**Comment by pGore33p** [comment]
No.

**Comment by pGore33p** [comment]
The Log:

Process Started: 00400000 C:\Users\Vítězslav\Downloads\OpenRCT\openrct2.exe
Database file: C:\Users\VTZSLA~1\AppData\Local\Temp\Rar$EXa0.865\x32\db\openrct2.exe.dd32
breakpoint at 006F08E7 set!
DLL Loaded: 77350000 C:\Windows\SysWOW64\ntdll.dll
DLL Unloaded: 00170000 
DLL Unloaded: 74D70000 
DLL Unloaded: 00170000 
DLL Unloaded: 00170000 
DLL Loaded: 74D70000 C:\Windows\SysWOW64\kernel32.dll
DLL Loaded: 752D0000 C:\Windows\SysWOW64\KernelBase.dll
DLL Loaded: 71EB0000 C:\Windows\SysWOW64\winmm.dll
DLL Loaded: 6C2E0000 C:\Windows\SysWOW64\ddraw.dll
DLL Loaded: 75130000 C:\Windows\SysWOW64\user32.dll
DLL Loaded: 76980000 C:\Windows\SysWOW64\gdi32.dll
DLL Loaded: 76A90000 C:\Windows\SysWOW64\comdlg32.dll
DLL Loaded: 76570000 C:\Windows\SysWOW64\advapi32.dll
DLL Loaded: 753A0000 C:\Windows\SysWOW64\shell32.dll
DLL Loaded: 6C410000 C:\Windows\SysWOW64\dinput.dll
DLL Loaded: 6C2A0000 C:\Windows\SysWOW64\dplayx.dll
DLL Loaded: 5C4D0000 C:\Windows\SysWOW64\dsound.dll
DLL Loaded: 6C170000 C:\Users\Vítězslav\Downloads\OpenRCT\openrct2.dll
DLL Loaded: 71E90000 C:\Windows\SysWOW64\winmmbase.dll
DLL Loaded: 75060000 C:\Windows\SysWOW64\msvcrt.dll
DLL Loaded: 6F7F0000 C:\Windows\SysWOW64\dciman32.dll
DLL Loaded: 767D0000 C:\Windows\SysWOW64\shlwapi.dll
DLL Loaded: 765F0000 C:\Windows\SysWOW64\comctl32.dll
DLL Loaded: 77240000 C:\Windows\SysWOW64\sechost.dll
DLL Loaded: 768D0000 C:\Windows\SysWOW64\rpcrt4.dll
DLL Loaded: 76B20000 C:\Windows\SysWOW64\combase.dll
DLL Loaded: 77130000 C:\Windows\SysWOW64\ole32.dll
DLL Loaded: 716E0000 C:\Windows\SysWOW64\powrprof.dll
DLL Loaded: 6C740000 C:\Users\Vítězslav\Downloads\OpenRCT\SDL2.dll
DLL Loaded: 75280000 C:\Windows\SysWOW64\cfgmgr32.dll
DLL Loaded: 74C30000 C:\Windows\SysWOW64\devobj.dll
DLL Loaded: 74D50000 C:\Windows\SysWOW64\sspicli.dll
DLL Loaded: 74F10000 C:\Windows\SysWOW64\imm32.dll
DLL Loaded: 77090000 C:\Windows\SysWOW64\oleaut32.dll
DLL Loaded: 74050000 C:\Windows\SysWOW64\version.dll
DLL Loaded: 72650000 C:\Windows\SysWOW64\SHCore.dll
DLL Loaded: 74D40000 C:\Windows\SysWOW64\cryptbase.dll
DLL Loaded: 74F60000 C:\Windows\SysWOW64\msctf.dll
DLL Loaded: 74CE0000 C:\Windows\SysWOW64\bcryptprimitives.dll
system breakpoint reached!
DLL Loaded: 71E10000 C:\Program Files (x86)\AVG\AVG2015\avghookx.dll
INT3 breakpoint "entry breakpoint" at 006F08E7!
breakpoint at 006F08E7 set!
INT3 breakpoint at 006F08E7!
DLL Loaded: 74CA0000 C:\Windows\SysWOW64\profapi.dll
DLL Loaded: 71D30000 C:\Windows\SysWOW64\uxtheme.dll
DLL Loaded: 744D0000 C:\Windows\SysWOW64\kernel.appcore.dll
DLL Loaded: 76E10000 C:\Windows\SysWOW64\clbcatq.dll
DLL Loaded: 02E20000 C:\Windows\SysWOW64\XAudio2_7.dll
DLL Loaded: 71780000 C:\Windows\SysWOW64\MMDevAPI.dll
DLL Loaded: 717D0000 C:\Windows\SysWOW64\mscms.dll
DLL Loaded: 74CC0000 C:\Windows\SysWOW64\userenv.dll
DLL Loaded: 59E50000 C:\Windows\SysWOW64\icm32.dll
DLL Loaded: 71850000 C:\Windows\SysWOW64\dwmapi.dll
Thread 1A48 created
DLL Loaded: 71720000 C:\Windows\SysWOW64\AudioSes.dll
Thread 1A0C created
Thread 1B2C created
Thread 8F8 created
Thread 1A10 created
Thread C0 created
Thread 1E38 created
DLL Loaded: 70540000 C:\Windows\SysWOW64\avrt.dll
first chance exception on 6C173F53 (C0000005, EXCEPTION_ACCESS_VIOLATION)!

**Comment by IntelOrca** [comment]
Did you compile OpenRCT2 yourself or get it from openrct2.com?

**Comment by pGore33p** [comment]
I just downloaded it... obviously??

**Comment by IntelOrca** [comment]
Okay thanks, I think its related to loading of sound files using the new mixer.

**Comment by pGore33p** [comment]
Wait what do you mean?

**Comment by IntelOrca** [comment]
Can you try this with the verbose flag please.
http://www.filedropper.com/openrct2

**Comment by pGore33p** [comment]
![bez nazvu2](https://cloud.githubusercontent.com/assets/10586092/6047052/88902ab4-aca7-11e4-8898-2db5a2ea7766.png)
Now you see the error?

**Comment by IntelOrca** [comment]
Thanks, can you now try this:
http://www.filedropper.com/openrct2_1

I am not sure why it can't load the sound file, but there was indeed a bug related to when it failed to load.

**Comment by pGore33p** [comment]
YES, IT WORKS!!!! IF WORKS!!

Thanks for solving this issue. THANKS A BUNCH.

You deserve a cookie: :cookie:

**Comment by IntelOrca** [comment]
Do you actually have any ride music or sounds?

**Comment by pGore33p** [comment]
... but it doesn't have sound... yup

**Comment by IntelOrca** [comment]
Try this, it should hopefully say why (run with verbose flag)
http://www.filedropper.com/showdownload.php/openrct2_2

**Comment by pGore33p** [comment]
It says that it couldn't open css2.dat

**Comment by IntelOrca** [comment]
OK, I think the most likely cause is string encoding. Sounds are being loaded with a function that expects UTF8 encoded filenames, where as all the filenames are currently stored as extended ASCII.

**Comment by pGore33p** [comment]
Oh come on I don't want to move my RCT folder. It has 2 Gigabytes!

**Comment by IntelOrca** [comment]
We will try to fix this soon. You may want to try it, just to make sure that, that is the problem though.

**Comment by pGore33p** [comment]
OK... we will stop chatting right now because there is 8 PM. And I am going to sleep. I am right now too tired from this xD thanks for fixing bro!
