### ISSUE TITLE
Crash when trying to build pre-built ride

### ISSUE THREAD

**Issue by yayachiken** [IntelOrca/OpenRCT2#703]
commit 1ece6e4a70f10cb0716470669485a39a6c019524

When trying to build one of the pre-built rollercoasters, the game crashes.

Steps to reproduce:
* Start wine openrct2.exe
* Start a scenario (I tried Rock'n'Roll - Flower Power, and Crazy Castle)
* Select a rollercoaster (e.g. Giga Coaster) from the rides menu (make sure that the new window does not spawn under your mouse cursor, otherwise you might accidentally automatically execute the next step and have the game crash)
* Hover mouse over one of the pre-built rides: The game crashes
* Alternative: Carefully select the option to build a custom ride without hovering over a pre-built ride: The game doesn't crash, and it is possible to build a ride

System: Arch Linux, 64 bit

**Comment by duncanspumpkin** [comment]
Probably the same issue as #606.

**Comment by duncanspumpkin** [comment]
Can you try making the changes suggested in #606. 
Edit https://github.com/IntelOrca/OpenRCT2/blob/develop/src/ride/track.c#L415 to the following.

`RCT2_CALLPROC_X(0x006D1EF0, 0, 0, 0, 0, 0, (uint8*)trackDesign + 163, 0);`

If you are not able to build it then I can upload a version with this change.

**Comment by yayachiken** [comment]
Yes, this seems to work nicely.
I am now able to build the pre-built rides.

**Comment by duncanspumpkin** [comment]
Okay that sounds good can you submit a PR for that change. If not I will make a PR sometime tomorrow. 

I might try remove RCT2_CALLPROC_EBPSAFE as its unsafe and replace it with CALLPROC_X with 0 for all parameters then some other little bugs might surface.

**Comment by yayachiken** [comment]
I'll let you have the honour, I am not involved as a programmer yet. :)

**Comment by IntelOrca** [comment]
Is this okay to be closed now?
