### ISSUE TITLE
Right-click on coaster doesn't open construction menu

### ISSUE THREAD

**Issue by RollingStar** [IntelOrca/OpenRCT2#706]
[Same save file as before](http://www.mediafire.com/download/hk5qsb9qg3ahwiq/Ghost_Town_RollingStar.SV6).

Pan up a small amount to the aqua coaster (Flying Coaster 1). Right click on it. Since it's closed, the construction menu should open. In ORCT2, it doesn't.

**Comment by duncanspumpkin** [comment]
Issue is caused by incorrectly using the x and y coordinates of the cursor instead of the x and y coordinates of the tile that the cursor is pointing at. I have a fix for it but just want to test one or two small things to make sure there are no inconsistancies between OpenRCT2 and RCT2.
