### ISSUE TITLE
Mechanics don't fix things

### ISSUE THREAD

**Issue by RM87** [IntelOrca/OpenRCT2#718]
After a 6 years of game running unsupervised by me with 1 only mechanic this is the result:
Mechanic was unable to fix some rides. 
Hired some additional mechanics.
Mechanics still cant fix some rides and can have a state of (X- non-fixable rides, Y-fixable rides):
* Answering radio call
* Responding to X/Y -either by being stuck in the ride that needs fixing, heading to ride X or wandering cluelessly around.
* Inspecting ride Y - everything works fine with some thrill rides
* fixing ride Y - everything works fine with some thrill rides
* drowning - happens sometimes on water based rides. This might be another bug or just a heavy loss of workers. Will hapen with this savegame in the next 5- 10 minutes multiple times.

savegame: http://web.zone.ee/rmihkel87-1/orct2/Botany_Breakers_c-water%20jam.SV6

**Comment by duncanspumpkin** [comment]
There are a variety of issues affecting the rides not getting fixed the main one is that mechanics keep getting reset what they are fixing. As this has happened whilst they are fixing a ride they end of stuck in unwalkable terrain.
