### ISSUE TITLE
Right Click on vehicles plays open window sound

### ISSUE THREAD

**Issue by duncanspumpkin** [IntelOrca/OpenRCT2#725]
As stated above this should only happen when the construct window appears.
Also in the original in contrast to all other right click items it would always open the ride window even if the ride couldnt be constructed on.

**Comment by adrian17** [comment]
Appeared in this commit: https://github.com/IntelOrca/OpenRCT2/commit/e0dbb

**Comment by adrian17** [comment]
Removing [this line](https://github.com/IntelOrca/OpenRCT2/blob/develop/src/ride/ride.c#L580) fixes it, I don't see if it breaks anything else.
