### ISSUE TITLE
Information kiosk has negative income

### ISSUE THREAD

**Issue by RM87** [IntelOrca/OpenRCT2#727]
![neg income](https://cloud.githubusercontent.com/assets/859636/5947209/0362265c-a744-11e4-8ea9-8a8b2c848e8c.png)

**Comment by IntelOrca** [comment]
Investigation required on **ride.c:223**:
```money32 ride_calculate_income_per_hour(rct_ride *ride)```

**Comment by duncanspumpkin** [comment]
https://github.com/IntelOrca/OpenRCT2/blob/develop/src/ride/ride.c#L250
There should be an add secondary price before that line. I will put a fix up later tonight if I have time.

**Comment by IntelOrca** [comment]
@duncanspumpkin Don't worry, I can sort this out.
