### ISSUE TITLE
Object Load File Failure

### ISSUE THREAD

**Issue by Superjustinbros** [IntelOrca/OpenRCT2#728]
Recently after several months since I last touched Open RCT2, I tried downloading the newest version, and when I launch the .exe, it takes a few more minutes than it should to load, then when it does this pops up:
"ERROR[..\src\object.c:90 (object_load_file)]: Object Load failed due to checksum failure.

The game does load eventually, and from there bouts don't take as long, but a few moments from starting a particular scenario, that game erupts.

Here's the scenario that the game's crashing on:
http://www.mediafire.com/download/8smu0sryfmm2b2o/CM36&#39;s_Izzio&#39;s_Fun_Park.SC6

**Comment by Superjustinbros** [comment]
The game is also having problems loading certain custom scenarios with custom items.

**Comment by duncanspumpkin** [comment]
Yeah we rewrote all of the object loading code so there might still be some little issues. The extra long load time is it building a new object list it only has to do this once. You may not remember it but the original game did this on the first load as well. I will take a look later tonight to see whats causing your issue with that scenario. Any other scenarios/objects your having issues with if you can provide links to them that would be great.

**Comment by duncanspumpkin** [comment]
The crash in CM36 is due to the park going right up to the edge of the map and when there is calculation for ride rating it takes into account scenery. Due to a little bug it tries to access a map element outside of map range.
