### ISSUE TITLE
'On-Ride Photo' profit value and wording wrong. 'Same price throughout park' tick does not stick

### ISSUE THREAD

**Issue by RM87** [IntelOrca/OpenRCT2#731]
![loss per item](https://cloud.githubusercontent.com/assets/859636/5965307/decdc45c-a803-11e4-941c-c8b507987dc9.png)
23.60 is a value  that comes from where?
Photos should make profit not loss.
Same price throughout park box in not always tickable (tick appears but does not stay).

**Comment by AaronVanGeffen** [comment]
Sounds like this may be related to #727 ­— which was fixed a few hours ago in 3d9235d2bd1789509011eafb912f795ef1dca159.
