### ISSUE TITLE
Select Currency based on OS's Reported Region

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#736]
For example, if the OS running the game claims to be from Canada or USA, use Dollars ($), or in a country that uses the Euro, switch to euro, and so on. This doesn't have to be implemented quickly or at all, but would be a nice thing to have.

**Comment by PFCKrutonium** [comment]
Just want to add to this, as it is in the same vein - change the Units (Imperial vs Metric) Based on the same data.

**Comment by Gymnasiast** [comment]
It would be a good idea, but only when no existing settings are present, like when the user starts OpenRCT2 for the first time. So if the user runs the game for the first time, it could use the OS info to determine currency, units and language to write a settings file.

**Comment by PFCKrutonium** [comment]
>Not too sure how you identify currency from the OS mind.

Just have a lookup table of countries to currencies, with a fallback so if the country is unknown, default to say euro.

**Comment by IntelOrca** [comment]
If someone would like to implement this for Windows:
[GetLocaleInfoEx](https://msdn.microsoft.com/en-us/library/dd318103(v=vs.85).aspx) with LOCALE_NAME_USER_DEFAULT might do the trick. The culture can then be used to get the best language, currency, number format etc. etc. as defaults if not override by the user.

**Comment by ThomasdenH** [comment]
Since it is implemented, the issue can be closed now.
