### ISSUE TITLE
Command Line to hide the Command Window (But output to log)

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#737]
Basically a way to hide the command prompt but keep the Command Prompt. I have experimented in my launcher with trying to hide the Prompt without hiding the actual game, but if I hide the prompt, it also hides the Game Window.

Maybe something like /noCMD or /hide or /q or... anything really.

**Comment by IntelOrca** [comment]
This is not quite possible as the original game executable is patched so that it is now a console application, changing it back would having no console at all. Eventually this will be changed and the game will include a built in console.

**Comment by PFCKrutonium** [comment]
Okay, thank you :+1:
