### ISSUE TITLE
Have Roller coasters Maintain name from Track File

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#738]
For example, if I build the Roller coaster "Great White Wail", it will be renamed to "Roller Coaster 1". Ideally, the name of the coaster should match the name that was given in the selection stage (Where you choose the track layout.).

**Comment by IntelOrca** [comment]
This is already the current behaviour... Are you currently experiencing this in OpenRCT2?

**Comment by duncanspumpkin** [comment]
I don't think it does do this right now in OpenRCT2. I would have to double check but I don't remember this happening.

**Comment by IntelOrca** [comment]
This used to be the case in RCT1, but RCT2 has always named the new ride with the name of the track design unless that name already exists for another ride or the park. As far as I can see, OpenRCT2 has not broken this behaviour.

**Comment by PFCKrutonium** [comment]
![scr2](https://cloud.githubusercontent.com/assets/3945538/6025770/178431ee-aba3-11e4-99a5-47ed3d34c295.png)

Here is an Image of the behavior manifesting.

**Comment by duncanspumpkin** [comment]
Sorry its a bug introduced by recent track_list work. Will try find the cause asap.

**Comment by PFCKrutonium** [comment]
Thanks :+1:

**Comment by IntelOrca** [comment]
@duncanspumpkin Interesting, it works for me with latest develop.

**Comment by duncanspumpkin** [comment]
It shouldn't it would seem that you are meant to copy the track name into 0x009E3504 before placing the track. This used to happen during load_track_design.
