### ISSUE TITLE
I have updated language_us.txt to have the strings in the cheats window

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#745]
This fixes #743 when Language is set to English(US).

I am new to using Git, so can someone explain to me how to submit it? (Or can I just upload the txt file and someone throw it in for me?)

**Comment by AaronVanGeffen** [comment]
First, fork the repository so you can edit it. If you like, you can then clone it to your computer through a Git client, edit it locally, then push your changes back online. Alternatively, you can edit the file online by browsing your copy of the OpenRCT2 repo, looking up the file and clicking the pencil icon in the top-right corner of the toolbar above it.

After your edits, you can submit a pull request to merge your changes back in the official OpenRCT repo.

**Comment by IntelOrca** [comment]
https://guides.github.com/activities/forking/

**Comment by PFCKrutonium** [comment]
In theory it is now waiting for the patch :)
