### ISSUE TITLE
Lots of Plusses

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#752]
![screenshot 8](https://cloud.githubusercontent.com/assets/3945538/6089658/51f95938-ae34-11e4-8b73-524951e64f67.png)

Not sure why these are here, but they are normally used to display expansion packs, of which there are 2, and I have both installed.

**Comment by PFCKrutonium** [comment]
I don't know why, but on subsequent launches they are gone... No idea why.

**Comment by RollingStar** [comment]
The text that normally goes after the pluses comes from the Windows registry.

    reg query "HKLM\SOFTWARE\Wow6432Node\Infogrames\RollerCoaster Tycoon 2 Setup"
    reg query "HKLM\SOFTWARE\Infogrames\RollerCoaster Tycoon 2 Setup"

Maybe ORCT2 failed to read from the registry.

**Comment by IntelOrca** [comment]
The code has been written to read the expansion packs from the registry but is not actually called.
```osinterface.c:565, osinterface_407978```

I don't plan to keep this feature anyway, the objects and scenarios that are part of the two expansion packs will work just like any other custom object.
