### ISSUE TITLE
Game still fails to download files from Scenarios/Saved Games

### ISSUE THREAD

**Issue by Superjustinbros** [IntelOrca/OpenRCT2#754]
Per the title above; I've been running into this problem quite a few times and have been unable to run specific scenarios or saved games because of checksum failures.

There's also the old tired bug where it tries to load those files every time the game is booted up after attempting to run a park with custom objects, only to force-close the status window, preventing the game from running. It closes too quickly for me to be able to screen cap it and show you guys what it looks like.

**Comment by PFCKrutonium** [comment]
Have you considered using a screen recorder?

**Comment by duncanspumpkin** [comment]
You can just output the console to a text document load up cmd.exe and cd to your OpenRCT2 directory and just do `openrct2.exe > log.txt` that way the console window will be copied into the text file. If you could provide any save files (and custom objects if required) where its failing that would be great.

**Comment by Superjustinbros** [comment]
Gotta love all these checksum failures. >_>
