### ISSUE TITLE
Doing openrct2.exe --verbose > lol.txt doesn't capture all text

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#756]
I did it and it and lol.txt only contained 

Starting OpenRCT2 v0.0.1
  Windows (x86)
  Feb  7 2015 19:01:28

Time: 2015/02/07 13:11:17

**Comment by adrian17** [comment]
`>` only redirects stdout, not stderr.

Try:

    openrct2.exe --verbose > lol.txt 2>&1

**Comment by PFCKrutonium** [comment]
That worked.
