### ISSUE TITLE
If you alt+tab out of a Fullscreen Game, the Game does not return to full screen.

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#758]

**Comment by adrian17** [comment]
You mean:

- start the game
- in the settings menu, switch to fullscreen
- alt-tab
- alt tab back
--> the game is now windowed?

Strange, seems to work properly for me.

**Comment by PFCKrutonium** [comment]
Oddly enough, right after I posted this it stopped this behavior... And I thought I put a description in. >.>
