### ISSUE TITLE
Peeps seem to be unable to use benches

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#760]
Save file attached:

https://mega.co.nz/#!mUEiCbKY!Tjjh0aFyuTu6oOBYpjg6Q7PIGHf-UQRy6pIYCRk6FzY

They just walk around, never sitting. Their legs must hurt ;)

As a side note, the game starts to get a bit laggy at around 1000 Peeps.

**Comment by PFCKrutonium** [comment]
It would seem from my Extensive Play recently (I was streaming OpenRCT2) They are also not able to use Garbage Cans. Some interaction code missing/broken maybe?

**Comment by duncanspumpkin** [comment]
I did test both garbage and bench code quite a bit so I'm surprised its not working. I will have a look and see what is happening. Might be related but I feel peeps seem to like to watch rides more than normal.

**Comment by duncanspumpkin** [comment]
Okay ive had a look and I have found that yes the peeps are not sitting and I have a fix for that. Also peeps were avoiding bins if they were on only certain sides of a path.

**Comment by duncanspumpkin** [comment]
Another super interesting bug is that bins will never fill up due to the way it does a cheeky roll of the dice to decide if the bin has increased in amount of rubbish.

**Comment by duncanspumpkin** [comment]
In addition to all of those bugs. There is also a bug in the handymen that will cause bins to refill if they are emptying a bin on a path with multiple bins.
