### ISSUE TITLE
Track preview broken

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#773]
Track preview doesn't show.

**Comment by duncanspumpkin** [comment]
Any more details on this. When i was playing about yesterday it was working fine.

**Comment by IntelOrca** [comment]
Perhaps a recent merge has broken it, I just can't ever get it to show a preview any more.

**Comment by duncanspumpkin** [comment]
I can't reproduce this. Is it happening on all rides?

**Comment by PFCKrutonium** [comment]
I can confirm it is broken for me as well.

**Comment by IntelOrca** [comment]
![image](https://cloud.githubusercontent.com/assets/1482259/6152720/4841bade-b217-11e4-8da7-6b02354cf852.png)
