### ISSUE TITLE
Crash loading Downloaded Save

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#777]
http://pastebin.com/UKH7DwK1 <- Verbose Log

http://www.nedesigns.com/park/1394/europa-park-world-showcase/ <- This Map.

As a note, that map has maxed out a couple things, including but not limited to banners and objects.

Simply crashes with no explanation, Log recorded Verbose.

Edit: Woo, #777

**Comment by duncanspumpkin** [comment]
Thanks for providing the logs and files I will take a look tonight. There is a high chance its crashing because of it maxing out certain objects. One of the previous crashes was caused by that.

**Comment by IntelOrca** [comment]
What objects is it maxing out on?
- Imported objects (720)?
- Sprites (10,000)?
- Rides (255)?
- Map elements (30,000)?

**Comment by PFCKrutonium** [comment]
If you download the map and open the zip, it has a readme file with details.

**Comment by duncanspumpkin** [comment]
Its crashing on vehicle update for me. Which shouldn't have anything to do with the number of objects or anything.

**Comment by duncanspumpkin** [comment]
I can get this save loading if I disable one of the checks for station track start. I have a feeling due to heavy 8 cars abuse this save shouldn't really load.

https://github.com/IntelOrca/OpenRCT2/blob/develop/src/ride/station.c#L317
If that line was changed so that it was just `while (mapElement++)` then the save loads.

**Comment by duncanspumpkin** [comment]
Not sure what we should do for this save make it spew out an error message about broken rides and still load the game or just force a reload saying the save is broken.

**Comment by Gymnasiast** [comment]
The save in question now loads correctly in OpenRCT2, so this can be closed.
