### ISSUE TITLE
Guests standing in Queue lines to watch rides 

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#781]
This is not vanilla behavior, and doesn't break anything, in fact it makes the park feel more dynamic, but I am reporting it since technically it *is* a bug. Perhaps tag as Won't Fix.

**Comment by duncanspumpkin** [comment]
Can you provide a save of this happening just to make it easier to test.

**Comment by PFCKrutonium** [comment]
https://www.dropbox.com/s/48633fjondpr66q/Leafy%20Lake%20-%20Standing%20In%20Queue.SV6?dl=1

**Comment by IntelOrca** [comment]
I also think guests are a bit generally too keen, more than usual...

![image](https://cloud.githubusercontent.com/assets/1482259/6200576/a55305a0-b476-11e4-872c-49669b67c1fd.png)

**Comment by PFCKrutonium** [comment]
Yes, I noticed this as well. If we could make them less keen, but keep them watching from Queue lines as appropriate, I feel that this will be a nice improvement that not everyone will notice.

**Comment by IntelOrca** [comment]
I think the peep watch ride code just needs an integrity check with the original assembly.
