### ISSUE TITLE
Viewport window doesn't fully redraw

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#784]
When you have another window over the top of a viewport window and try to zoom in or out using the mouse wheel on that viewport window... the window is not repainting from the left side of the foreground window onwards (see screenshot).

![image](https://cloud.githubusercontent.com/assets/1482259/6158125/66ea944c-b23f-11e4-929d-3dbd896b0154.png)

**Comment by duncanspumpkin** [comment]
I have a cheap solution to this. We just call bring to front whenever you scroll on the viewport. What do you think?

**Comment by IntelOrca** [comment]
Sure, just write a // HACK there so we can improve it at a later date.
