### ISSUE TITLE
Cheat Request: Fix and Break Rides

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#786]
Basically, the ability to enable a cheat and click on a ride (or maybe just effect every ride) to either break down or repair rides.

**Comment by runelaenen** [comment]
Why would you want to break a ride? :p

**Comment by PFCKrutonium** [comment]
For testing things like #785

**Comment by PFCKrutonium** [comment]
Also, to fuck with my peeps XD
