### ISSUE TITLE
Removal of old audio code

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#794]
All the sound and music is software buffered and played using SDL. Is there any reason not to remove the original audio code now (all the code guarded from ```USE_MIXER```)?

**Comment by PFCKrutonium** [comment]
Based on the lack of response I want to say it would be okay to remove it. If someone complains, you will know why.

**Comment by zsilencer** [comment]
I put those in so if there's any problems such as #852 it can easily go back to using directsound only and to test if there is any differences.  Should be removed only when necessary such as when the game is ready to be compiled natively and cannot use directsound.

**Comment by IntelOrca** [comment]
OK, before #852 I was convinced it was working perfectly.
