### ISSUE TITLE
Building on Linux Fails

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#795]
I followed the instructions [Here](https://github.com/IntelOrca/OpenRCT2/wiki/Building-OpenRCT2-on-Linux), but when it gets to the actual build, the following error occurs:

bash build.sh
~/Desktop/OpenRCT2/build ~/Desktop/OpenRCT2
build.sh: line 10: cmake: command not found

**Comment by vzybilly** [comment]
Judging from the one line, I would say that you don't have cmake installed?

I don't have much time now but I'm pretty sure that's the issue... I'll look into it more later.

**Comment by IntelOrca** [comment]
Yes, you need cmake...
```
apt-get install cmake
yum install cmake
```

**Comment by PFCKrutonium** [comment]
That worked - and now I am trying to figure out why I didn't try that...

In any case, perhaps that should be added to the install.sh?

**Comment by PFCKrutonium** [comment]
err:ole:CoGetClassObject class {5a508685-a254-4fba-9b82-9a24b00306af} not registered
err:ole:CoGetClassObject no class object {5a508685-a254-4fba-9b82-9a24b00306af} could be created for context 0x1
ERROR /root/Desktop/OpenRCT2/src/scenario_list.c:scenario_scores_load():188: Unable to load scenario scores.
fixme:win:EnumDisplayDevicesW ((null),0,0x32f964,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32f964,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32f4b8,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x32f964,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x32f964,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x32f964,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x32f964,0x00000000), stub!
fixme:imm:ImmReleaseContext (0x100da, 0x132480): stub
fixme:ole:CoCreateInstance no instance created for interface {3e90ade3-7594-4cb0-bb58-69628f5f458c} of class {529a9e6b-6587-4f23-ab9e-9c7d683e3c50}, hres is 0x80004002
fixme:imm:NotifyIME NI_CLOSECANDIDATE
fixme:imm:NotifyIME NI_CLOSECANDIDATE
fixme:imm:NotifyIME NI_CLOSECANDIDATE


It compiles and runs (Woot!), but the console contains this, just so you know.

**Comment by IntelOrca** [comment]
This is known... not sure why Wine hasn't implemented those methods... But not too bothered in the long run.
