### ISSUE TITLE
OpenRCT crashing on start up after loading custom scenario

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#796]
Source: http://www.reddit.com/r/openrct2/comments/2vtsd0/openrct_crashing_on_start_up/

Hi,
I've been using OpenRCT2 for a couple of days now via the launcher (http://www.reddit.com/r/openrct2/comments/2ul8qg/openrct2_updaterlauncher/). Just now I tried opening a custom scenario and it crashed, and now I can't open OpenRCT2 at all. I've tried downloading the latest version and the one before that from GitHub but both crash at the same time. Here's the screenshot from command prompt: http://i.imgur.com/izw1tK4.png (Well as much as I could fit, if it outputs a log file please point me in the right direction).
I'm not expecting a quick fix, but I do hope I can help bring awareness to a possibly unknown error for future builds :) If you have any ideas I'm all ears; vanilla RCT2 loads just fine (TT, gog copy)

**Comment by IntelOrca** [comment]
If the user reports that deleting plugin.dat fixes the game, then its most likely the same problem as #698 where I said that it should be able to create plugin.dat if it is corrupt.

**Comment by duncanspumpkin** [comment]
The user did report that deleting plugin.dat fixed the game so looks like we can mark this as duplicate.
