### ISSUE TITLE
Map Generator: Expose Simplex noise key parameters in menu for random maps

### ISSUE THREAD

**Issue by nbrochu** [IntelOrca/OpenRCT2#804]
First off, having an in-game map generator is amazing. Great job on this!

This being said, I started playing around with it and found that the maps it generates have way too many height variations to be considered playable around 90% of the time.

I setup the project locally and started experimenting with the key parameters of the Simplex Noise generator and ended up with better/more consistent results.

I could submit a pull request with my findings but what I'm thinking is that what is considered a good map is very subjective. The best solution might just be to expose the parameters and let people come up with settings they prefer.

I'd love to participate on this, but I'll admit that the window system is pretty intimidating!

**Comment by nbrochu** [comment]
Here's what I mean by too many height variations:

![scr1](https://cloud.githubusercontent.com/assets/35039/6202602/ecb57166-b4c2-11e4-9995-c7994275464b.png)

![scr2](https://cloud.githubusercontent.com/assets/35039/6202605/1947d26e-b4c3-11e4-94b3-b5437dd46beb.png)


It looks nice, but good luck building a park on that!

**Comment by IntelOrca** [comment]
Yea, I would really like to spend more time on this, but I should be focusing my time on other parts of the game. So please, feel free to improve it. If you find the window system tedious, start off by just adding the extra parameters to the ```mapgen_settings``` struct with default values. The controls can be added later.

**Comment by nbrochu** [comment]
I'd definitely enjoy helping fleshing out the map generator. I'll play around with the window system until it clicks, no worries. It's going to be worth it long term.

Here's an example of something I can generate consistently at this point:

![scr5](https://cloud.githubusercontent.com/assets/35039/6202830/cfe5d138-b4cd-11e4-8bce-6870deb0aa05.png)

Not as sexy, but playable!

I'll be away for about a week and then I'll start working on a branch.

**Comment by Kavukamari** [comment]
what about having another larger noise underneath everything as a factor for the rough noise? that way there will be smooth parts and there will be rough parts interspersed together

**Comment by IntelOrca** [comment]
@Kavukamari It does do that in a way using Fractional Brownian motion.
@nbrochu Cool, although its still representing a map where a tile would be 100m² rather than like 1m².

Really we want presets with parameters like:

* Beach
* Lakes
  * Number of lakes
  * Size
* Forest
  * Clearing size
* Mountains
  * Roughness
* Mine
* Garden
* River
* Islands
  * Number of islands
* Desert
  * Smoothness
* Cliff side
  * Height
  * Number of cliffs or crevasse like
* Valley
* Hills

etc. etc.

**Comment by nbrochu** [comment]
Totally in agreement. Using a single layer of noise, even if using Fractional Brownian motion is not enough to have interesting features. The long term goal should be to have access to biomes/terrain features and that could be done with multiple passes and very specific code.

In the meantime, I managed to ship a little something. Check out #814. I added another tab that exposes the key parameters of simplex_mapgen. Window system isn't that complicated after all (but tedious, yes). I would consider it Step 0. Step 1 would be to have similar functionality but using more user-friendly terminology (Water Quantity, Hilliness, Height Variation etc.). Step 2+ is moving towards biomes and terrain features.

**Comment by RobertWHurst** [comment]
Would it be possible to have the generator produce a clearing for park land on demand? I'm thinking something along the lines of dividing the park area into 9 zones. Each zone you could select the type of generation style. For example if I want to create a park next to an ocean on the west side, and a mountain range on the east side, I could set the three quadrants along the west to "ocean", the center three to "meadow", and the three along the east to "mountain".

Clearly what I'm proposing here is a lot more complex, but I thought I might throw it out for you guys to mill over.

I've been watching the project for awhile now, and It's really coming along. A big cheers :beers: to all of the contributors. Nice work!

**Comment by IntelOrca** [comment]
@RobertWHurst I was thinking of a the same kind of approach. Essentially some kind of recursive subdivision where you start off with an initial profile of what the basic map should look like on a low resolution (9x9), and then the generator would keep subdividing that 9x9 to increase the detail and size.

**Comment by RobertWHurst** [comment]
@IntelOrca Sounds good to me :)
