### ISSUE TITLE
Scenery window scrolling is buggy

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#805]
I recently fixed the scrolling bug in scenery that made it unusable, however it still has problems - just not bad.

**Comment by duncanspumpkin** [comment]
This is being caused by failing to update the widget height before calculating the tab sizes. I can create a hack for fixing this by placing a window_event_invalidate_call(w) in the window_scenery_resize function but I'm not sure what is causing the underlying issue.
