### ISSUE TITLE
Wrong fullscreen resolution

### ISSUE THREAD

**Issue by ipatix** [IntelOrca/OpenRCT2#810]
So I have a 16:10 1680x1050 monitor and oRCT2 offers me 3 (correct) fullscreen resolutions: 1280x800, 1440x900 and 1680x1050.
The thing is that selecting 1280x800 doesn't seem to produce 1280x800. The resulting display resolution has an 4:3 aspect ratio and is most likely 800x600 or something (like the UI is big enough for blind people but not 640x480) instead of 1280x800.

**Comment by PFCKrutonium** [comment]
![screenshot 16](https://cloud.githubusercontent.com/assets/3945538/6205609/119cd92c-b542-11e4-94d3-23aaef6d07d0.png)

Yah, same for me. I generally use the Desktop resolution setting though.
