### ISSUE TITLE
Lag issue in scenery building mode

### ISSUE THREAD

**Issue by ipatix** [IntelOrca/OpenRCT2#811]
Not sure if this one is a bug, but selecting an item from the scenery building menu seems to heavily slow down the game (like almost twice as slow!) and I don't remember having that issue in the original RCT2. When exiting the building menu the game speed goes back normal.

Edit: Just to be mentioned: I'm running an AMD Phenom II X2, 3.4 GHz CPU and even at university it lags on Intel Haswell CPUs (not sure which ones).

**Comment by RobertWHurst** [comment]
I also noticed this lag when playing.

**Comment by PFCKrutonium** [comment]
I have also noticed this lag when I simply opened the menu. i7 2630QM 2.7Ghz.
