### ISSUE TITLE
"???" labels everywhere

### ISSUE THREAD

**Issue by ipatix** [IntelOrca/OpenRCT2#812]
I'm a little curious that noone has talked about this yet (or maybe I missed it) but since about one or two weeks something broke the game and a lot of the text labels show "???".
This includes like critical stuff like the current date (would be nice to know when doing time limited scenarios). Here's a shot list where I found those bugged labels:
- current date on the HUD
- ride test results
- sound/music options
- save loading menu offers a "???" button

This seems to happen regardless to which language I'm using. This issue seems to occur even when using English language.

![screenshot 085 openrct2](https://cloud.githubusercontent.com/assets/8502545/6205581/9887346a-b573-11e4-80b7-11c8c00523aa.png)

**Comment by adrian17** [comment]
Actually, all of these are the new translatable strings - no one has written a German translation for them yet. I think some kind of "fall back to English when translation is not available" behavior would be cool, but I'm not sure if that can be implemented just yet.

> This issue seems to occur even when using English language.
That is weird. Did you try both English(US) and English(UK)? Could you please post a screenshot?

**Comment by ipatix** [comment]
There we go:
![screenshot 086 openrct2](https://cloud.githubusercontent.com/assets/8502545/6205768/137f794c-b57a-11e4-9134-57ef5bd754d0.png)

**Comment by adrian17** [comment]
Could you check in the data/language/english_us.txt file, what are the contents of strings STR_2720 to STR_2743?

**Comment by ipatix** [comment]
Oh man, I feel so derpy. So the strings are "???" and this pretty much told me that I must have forgotten to update the language files.
My bad, I'm sorry for that terrible mistake I did :D

**Comment by RollingStar** [comment]
As a kludge to do a kind of "language fallback", one could compare the translation with the UK text file and overwrite any of the ??? with the English text, or with English + ??? to signify that they need to be changed.

**Comment by ipatix** [comment]
Actually, I just found another flaw with those ??? labels.
If I load a scenario by passing it on command line to openrct2.exe I get the same problem as mentioned my screenshot above (this does not happen when loading it regulary). I opened the settings ingame and all available language (which I set to en-US previously) are "???".

Also, I found out that the issue above also happens when running the game with Wine on Linux (Debian Wheezy in my case). You can only select "???" language in the settings and even forcing it to en-US in the config file doesn't solve the problem. Other than that I don't expect you to fix missbehaviour with Wine because it could possible Wine's fault.
