### ISSUE TITLE
Guest tracking messages have an empty icon in the Recent Messages window

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#817]
![scr3](https://cloud.githubusercontent.com/assets/1478678/6227790/72db3680-b6a4-11e4-960a-67cbc5252e43.png)

See the screenshot. The messages that you get when tracking guests have an empty icon. Vanilla RCT2 shows an image of that guest there.

**Comment by duncanspumpkin** [comment]
https://github.com/IntelOrca/OpenRCT2/blob/develop/src/windows/news.c#L342-L347

Code has not been written

**Comment by IntelOrca** [comment]
I think the bottom news bar may also be missing the code to render a peep.

**Comment by duncanspumpkin** [comment]
Yup bottom toolbar also missing code https://github.com/IntelOrca/OpenRCT2/blob/develop/src/windows/game_bottom_toolbar.c#L565-L657
