### ISSUE TITLE
Map Generator improvements

### ISSUE THREAD

**Issue by pGore33p** [IntelOrca/OpenRCT2#829]
I have 4 improvements that can be fixed in the map generator...

1. Third tab is showing ??? instead of text (using english version)
2. Some of the tabs are useless and need to be all in one tab to avoid confusion
3. More implementations on 2th tabs (footpaths or something like that)
4. No Icons?

![bez nazvu](https://cloud.githubusercontent.com/assets/10586092/6266443/320c652e-b83a-11e4-8d69-6a074b1f9f44.jpg)

**Comment by duncanspumpkin** [comment]
1. ??? is showing up as the strings are not loading. As the developer of the thrid tab was using US english it looks like the strings have not been copied across into english UK. Feel free to fix that and submit a PR. 
2. The map generator is in very early stages of development. I think the main idea of separating it into tabs is to expose different settings. 3rd tab is an advanced version of the 2nd tab for example. There will no doubt be lots of changes in layout over the next couple weeks.
3. When someone comes up with a suitable algorithm for footpaths im sure that will be added but at present its just for generating landscapes.
4. We cant do custom icons yet so thats the reason why its blank.

**Comment by pGore33p** [comment]
I was thinking I am good at making RCT2 like icons but I am completely stupid as a developer (I am not one) and I can send you some thing I made 31329734 years ago

**Comment by IntelOrca** [comment]
@pGore33p Are you able to make animated icons using the RCT2 palette? You could make them now, ready for when we are able to implement them.

**Comment by pGore33p** [comment]
I can make it in GIF but I am not sure what the RCT2 pallete is...

**Comment by IntelOrca** [comment]
See #804.
