### ISSUE TITLE
Tree in footpath

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#830]
In scenario Bottany Breakers there are trees by default. I can place a footpath under the tree like on the screenshot. I don't think that should be happening. :p 
![Imgur](http://i.imgur.com/qHagFxv.png)
It happens with all trees and scenery, also the ones I put there myself.
![Imgur](http://i.imgur.com/cYskB2W.png)

**Comment by duncanspumpkin** [comment]
how odd. Did this happen in the original? Sounds like a clearance issue.

**Comment by Gymnasiast** [comment]
No, it doesn't. I have also had this in the Scenario Editor. I have also tried it in several saved games, and _all_ of them have this issue. It's an OpenRCT2 bug. You can probably reproduce it in every saved game and scenario.

**Comment by IntelOrca** [comment]
It will probably be related to ```footpath_element_insert``` and the unwritten function 0x006A6733 which is a callback for the automatic scenery removal function.
