### ISSUE TITLE
Deleting a Piece of Path with a Sign on it Causes a Crash

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#834]
https://www.dropbox.com/s/gizgjwtkhy8kyed/Sign%20Crash.sv6?dl=1

Load that map, and try to delete the piece of path with the sign on it. The game will immediately crash.

**Comment by Gymnasiast** [comment]
Does it happen in vanilla RCT2? And does it happen with other saved games?

**Comment by PFCKrutonium** [comment]
Confirmed doesn't crash RCT2, and all scenarios.
