### ISSUE TITLE
Small terrain generation glitches

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#840]
When generating a landscape in the scenario editor, the terrain sometimes contains tiles that don't smoothly connect to others. Reproduceable by generating a few random terrains until you get one like this.
![scr4](https://cloud.githubusercontent.com/assets/1478678/6284392/d28c8d7a-b8ef-11e4-896d-7d43827d9a00.png)

**Comment by IntelOrca** [comment]
Yes, I unfortunately don't now how to fix this very easily as I can't work out why it happens. If someone has a better solution for smoothing map tiles, feel free to edit
```map_helpers.c::map_smooth```
