### ISSUE TITLE
Land ownership tool only allows a 7x7 area to be modified.

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#841]
This _is_ vanilla (and intended) behaviour, and more of a feature request. But since both the land and water tool now allow modifying an area much larger than 7x7, I think it makes sense to raise this limit on the land ownership tool in the scenario editor as well.

**Comment by cowan108** [comment]
Better yet, an "Own All Land" button would be awesome too.

**Comment by PFCKrutonium** [comment]
Commenting since I also want this.
