### ISSUE TITLE
Guest go out of the wating queue

### ISSUE THREAD

**Issue by runelaenen** [IntelOrca/OpenRCT2#843]
If a ride is to expensive and peeps decide not to enter the ride, they will leave the queue. Sometimes by going back (normal Vanilla behaviour), but sometimes by just 'climbing over the railing'
![Imgur](http://i.imgur.com/sfDLwA4.png)

**Comment by runelaenen** [comment]
Hmm doesn't seem to be that cause (just tested it on another ride)
However, the peeps still shouldn't be able to get on the grass I think?

**Comment by IntelOrca** [comment]
Can you provide a saved game where this happens?

**Comment by runelaenen** [comment]
I would say yes, but for some reason it stopped happening :/

**Comment by runelaenen** [comment]
https://www.dropbox.com/s/gscwy2zoyu3cykl/six%20flags%20belgium%20-%20kopie.sv6?dl=0

**Comment by duncanspumpkin** [comment]
I've known about this one for a while but thought it only occurred when you closed rides and then went into construct mode (i.e. force all peeps off ride).

**Comment by duncanspumpkin** [comment]
@runelaenen can you try reproduce this bug. I've changed a little mistake in the peep code that i think was causing this but can't be too sure.

**Comment by runelaenen** [comment]
I dont have any time today but ill try tomorrow at school :-)

**Comment by ThomasdenH** [comment]
I can't reproduce it anymore in the save.
