### ISSUE TITLE
Rides breaking down Very Frequently (too Frequently)

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#851]
https://www.dropbox.com/s/ikx78dmg1vka276/Crazy%20Castle_BrokenRides.SV6?dl=0

They break down way to frequently - Sometimes seconds after the mechanic leaves.

**Comment by tehplanefreak** [comment]
Are you using a trainer?

**Comment by ipatix** [comment]
I've experienced something similar. Don't have the save file around at home but I can supply one later if necessary.
Like FPCKrutonium said, some rides literally break instantly after being repaired. If you have one of those "infected" rides the issue won't go away by itself.
