### ISSUE TITLE
Some numbers and menus appearing as '???'

### ISSUE THREAD

**Issue by Enzemo** [IntelOrca/OpenRCT2#862]
Hi,

I was using OpenRCT as normal and then saved and reloaded a little later and some numbers weren't appearing.

I was running from the windows installer, downloaded about an hour ago from this post. First run was fine, every subsequent has given the error.

Please see the imgur links for examples. Some menus aren't showing either. Please excuse my noob park design and thank you for all the help and support

![scr4](https://cloud.githubusercontent.com/assets/11069930/6323237/81015428-bb1e-11e4-92b6-be6d30c21bd3.png)
![scr5](https://cloud.githubusercontent.com/assets/11069930/6323236/8100d368-bb1e-11e4-89ad-2679804c5811.png)

**Comment by PFCKrutonium** [comment]
What do you have your language set to?

**Comment by JarnoVgr** [comment]
As PFCKrutonium says this is most likely caused by outdated language files. Try to switch to 'English (UK)'.

**Comment by Enzemo** [comment]
Very odd. English UK; it's the only language I speak.

**Comment by duncanspumpkin** [comment]
I'm more concerned about the numbers being ??? that should only happen when the ride is doing its first couple runs. Can you provide a copy of your save?

The dialogs having ??? is because its failing to load the language file its normally caused by the .exe file being run from a different directory.

**Comment by jtuc** [comment]
Just want to confirm this isn't an isolated issue. I've tried deleting the folder in Documents and reinstalling OpenRCT2 - neither fixes the issue. I do have a little bit of custom content installed for RCT2 - could this be causing the problem? Using build 449 on Windows 8.0 x64.

![1](https://cloud.githubusercontent.com/assets/6748724/6331941/4cde75ca-bb7a-11e4-91ed-3d257afae876.png)
![2](https://cloud.githubusercontent.com/assets/6748724/6331944/4e38ce8e-bb7a-11e4-9cd9-45d66de3499b.png)
![3](https://cloud.githubusercontent.com/assets/6748724/6332020/c4f7d330-bb7a-11e4-9690-04178defdca5.png)

**Comment by ThomasdenH** [comment]
The issue is that somehow the language files in Program Files are not being updated. Manually copying the latest files into the directory fixes it.

**Comment by Enzemo** [comment]
I will provide my save when I'm home from work. I think it does have some
custom scenary to be honest. My install directory is f:\program files
(x86)\gogcom\ then the standard triple thrill pack folder title. Could it
be because it's not installed to C:\?

I will also copy over my language files tonight to try fix. Thanks all.
Much appreciated.

**Comment by Enzemo** [comment]
Oh, and my OS is windows 7 premium, I'm unsure of the build, I will also
check that for you. Think it's 7600 though.

**Comment by ThomasdenH** [comment]
Ah. The prebuilt binaries seem to be using outdated language strings. Both 499 and 450 have strings that do not correspond to the last commit, so at least some of the question marks can be explained by that.

**Comment by JarnoVgr** [comment]
@ThomasdenH Is only the installer affected, or the portable ZIP as well?

**Comment by jtuc** [comment]
@ThomasdenH Yes; replacing my language files with those from https://github.com/IntelOrca/OpenRCT2/commit/b5d0c3466b182cc4a9c2a768f360e08e48310167 seems to have fixed the problem on my machine. Thanks!

**Comment by ThomasdenH** [comment]
@JarnoVgr  Both have the problem.

**Comment by JarnoVgr** [comment]
@ThomasdenH I downloaded build 450 (ZIP) and it has the correct language files (with the changes mentioned in the commit from jtuc's reply). Or is there something else missing?

**Comment by Enzemo** [comment]
Okay so I just installed build 451 and the problem is still prevalent. I can't find my language files in the RCT install folder, what should I be looking for here?

Attached is the gamesave that I was playing on. It was running fine and I literally just closed and reopened it (Accidently clicked the X) and the text wasn't working.

http://www.filedropper.com/trains

**Comment by Enzemo** [comment]
Sorry to double post but this is worth an update in itself. I just loaded OpenRCT2 via the automatic updater program that is on Reddit and the game ran fine. It's worth mentioning that the update failed so it may be running on an older version of OpenRCT2, im not sure how to check which

**Comment by PFCKrutonium** [comment]
Hello, I am the person who runs the repo for the Launcher - 
 It's worth mentioning that the update

Can you please post the exact error?

**Comment by Enzemo** [comment]
Huh, dont know what went wrong with the upload, i'll try another site http://www.megafileupload.com/en/file/611961/Trains-sv6.html

I've posted the error on reddit previously, it was the following:
http://imgur.com/eVT23Qa You told me it was something blocking the connection, although I don't use a firewall  (Terrible I know) and it works sometimes

**Comment by PFCKrutonium** [comment]
:P I try :)

**Comment by JarnoVgr** [comment]
PR868 should fix this issue with the installer. The bug was, most likely, introduced when the build process was changed.

**Comment by ThomasdenH** [comment]
I was mistaken, the issue indeed wasn't in the .zips and only in the installer.
