### ISSUE TITLE
Rename ride issues

### ISSUE THREAD

**Issue by MisterSchmidt** [IntelOrca/OpenRCT2#872]
Hey i've played the game for quite some time now and found a few bugs or issues.. 

This is one of them:

When I tried to rename a ride like XII to X2 it told me that the name already existed. (when its not)
"Can't rename ride/attraction... Chosen name in use already" is the error.

![2error](https://cloud.githubusercontent.com/assets/11180804/6377557/4ae3a48c-bd25-11e4-9bc9-251cc83a324c.jpg)

It has probably something to do with the 2 or higher because I have no problems with renaming the ride to X or X1. Same happend to other rides with a 2 or 3 in it.

**Comment by PFCKrutonium** [comment]
Odd, it is like it understands roman numerals lol.

**Comment by IntelOrca** [comment]
Are any peeps, staff members, park name, banners etc. called X2?

**Comment by MisterSchmidt** [comment]
No nothing at all. Must say my save file could be corrupt tho

**Comment by IntelOrca** [comment]
Can you upload your save please.
