### ISSUE TITLE
Vouchers or marketing for ride problems

### ISSUE THREAD

**Issue by MisterSchmidt** [IntelOrca/OpenRCT2#874]
This happens while advertising or give away vouchers for a paticular ride

Sometimes this happens (there are a lot of double names)

![doublenames](https://cloud.githubusercontent.com/assets/11180804/6377886/b5613c46-bd27-11e4-972f-66f2a657f909.jpg)

And sometimes this happens: (no results)

![or-no-names](https://cloud.githubusercontent.com/assets/11180804/6377889/ba7e8e7c-bd27-11e4-94b8-65a4e1ae049d.jpg)

And sometimes its not even possible to advertise (the selection is grayed out)

My park is set to enterance money so thats probably why vouchers don't work. But the advertising should work in my opinion.

**Comment by runelaenen** [comment]
While I haven't had these errors. I have had the error that instead of the selected ride, Restroom 2 gets the advertising campaign...

**Comment by IntelOrca** [comment]
Could you now try my latest commit. If there are still problems, could you send me the saved game which has these problems. Thanks.

**Comment by MisterSchmidt** [comment]
I must say there is something changed. Now I get this (same as runelaenen was talking about). Also I can send you the save-file but you need to have some custom scenery witch I dont included in this save-game (so probably runelaenen can send his save file?)

![sameproblem](https://cloud.githubusercontent.com/assets/11180804/6378334/04970248-bd2b-11e4-8417-daba2ce221b3.jpg)

**Comment by runelaenen** [comment]
No, I could actually select the proper ride, but once running, the overview would say it was a campaign for the toilet.

**Comment by IntelOrca** [comment]
Okay, could you try again with this latest commit?

**Comment by IntelOrca** [comment]
Is anyone still able to reproduce this bug?

**Comment by MisterSchmidt** [comment]
Nope, im sorry for the late response.. It must be my corrupted save-game (doesn't matter anymore)
