### ISSUE TITLE
Cheat Window not Accessible on OS X

### ISSUE THREAD

**Issue by Phasedetect** [IntelOrca/OpenRCT2#890]
Due to the way that Wine handles modifier keys, there isn't a way to get to the cheats window on OS X.

**Comment by duncanspumpkin** [comment]
How does wine handle modifiers?

**Comment by mzmiric5** [comment]
"Ctrl+Alt+C now toggles the cheat window (On Mac, Wine driver for key mapping has issues so Alt is Cmd unless you patched the driver/config or have custom built wine)" - from #591

**Comment by Gymnasiast** [comment]
Does Cmd+Ctrl+C work?

**Comment by Phasedetect** [comment]
Thank you for the replies. I'm a little embarrassed, when I looked into the issue I didn't find anything, but I guess I didn't look deep enough. Cmd+Ctrl+C does indeed work. I changed the [wiki page] (https://github.com/IntelOrca/OpenRCT2/wiki/Changes-to-original-game) to reflect this.
