### ISSUE TITLE
Title sequence parks required!

### ISSUE THREAD

**Issue by IntelOrca** [IntelOrca/OpenRCT2#903]
These have already been requested for in the past, and some parks have already been submitted - but more are needed.

Please create parks to be shown in the title sequence in a similar fashion to RCT1. Parks do **NOT** need to be filled up or be compact. The RCT1 sequence was mostly filled with a mixture of quiet and busy parks which were just the initial state of scenarios. For example one park might just be a stream train travelling around an empty mine and another park showing off a duelling coaster.

Please **ONLY** use RCT2 vanilla objects, do not use objects from expansion packs or anywhere else as some people will not have them and distributing them will increase the game release size.

Here are some ideas:
* A quiet ski resort in the mountains with a chairlift and bob-sleigh coaster.
* Peeps walking through some gardens, maybe containing some hedge mazes.
* Duelling coasters going around a mine.
* A double track railway going round a lake and through tunnels.
* A food court and some small attractions on a beach.

You can either upload them and post a link or send them to me via e-mail.
Thanks.

**Comment by RobertWHurst** [comment]
Sounds like fun. I'll see what I can come up with.

**Comment by PFCKrutonium** [comment]
![electric fields sv6](https://cloud.githubusercontent.com/assets/3945538/6567547/9053fdc2-c69f-11e4-89d0-d1673d399ff9.png)

In theory, right click -> Save and rename to .sv6

Just something I threw together.

**Comment by gijsdaboss** [comment]
i have a few parks from the nedesigns.com database that are without custom scenery that would be good to use.

first of all hidden valley by JDP

http://www.nedesigns.com/park/1855/hidden-valley/

second one is rougarou by shotguns

http://www.nedesigns.com/park/3107/rougarou/

and then the best of them all Kidron park. this one is probably the best to put in there

http://www.nedesigns.com/park/3089/kidron-park/

could be that you like some others from the NE database more, in that case visit this page http://www.nedesigns.com/tag/223/ncso/?where=parks but be aware that some parks might contain custom pathing imported from rct1 (which i'd love to see getting added into Open rct as rct2 doesn't have enough pathing options IMO)

**Comment by IntelOrca** [comment]
@gijsdaboss Have the owners of these parks provided permission to use them?

My plan is for all RCT1 features to be fully supported in OpenRCT2.

**Comment by gijsdaboss** [comment]
i'll message them. getting JDP's approval seems difficult since he's no longer active IIRC. however RCT2day and Shotguns are. i'll PM them on NE. i'll let you know as soon as possible

**Comment by gijsdaboss** [comment]
by the way do you have an account on NE? in that case i can invite you to the PM's so you can know for sure. all i can do right now is provide screenshots which i can see as being a bit unreliable.

shotguns already replied about rougarou, we have his permission

http://i.imgur.com/IdAZKZr.png

**Comment by gijsdaboss** [comment]
rct2day gives his permission to have Kidron Park at the start menu as well

http://i.imgur.com/UTJ6iXx.png

again, i can always put you in the PM sessions to have full confirmation

**Comment by IntelOrca** [comment]
@gijsdaboss The screenshots are fine, thanks.

**Comment by IntelOrca** [comment]
I think Kidron Park uses several non-vanilla objects:
* AE-CUPS
* AE-SWING
* AE-WHIRL
* HOPPER01

**Comment by gijsdaboss** [comment]
oh, well i can always take them out, looks like they're some minor custom flats that can easily be replaced. i'll post an updated version soon

**Comment by RCTMASTA** [comment]
@gijsdaboss 
You could try e-mailing JDP at the address on his profile, but I don't know if/when he'd respond.

**Comment by PFCKrutonium** [comment]
https://www.dropbox.com/s/svuslxw8uw9famj/Build%20your%20own%20Six%20Flags%20Park%20-%20TitlePark.sv6?dl=1

![scr2](https://cloud.githubusercontent.com/assets/3945538/6587869/62c223ea-c760-11e4-884b-fe19e50316e5.png)

Another submission :P

**Comment by gijsdaboss** [comment]
okay so i've got a longer list now by searching the NE database, these parks should have no custom things at all

- Tussauds Magical Kingdom http://www.nedesigns.com/park/2861/tussauds-magical-kingdom/
 
- Floyds Family Farm http://www.nedesigns.com/park/665/floyds-family-farm/
 
- Märchen Paradies http://www.nedesigns.com/park/2973/maerchen-paradies/
 
- Fizzix's Electric Fields http://www.nedesigns.com/park/2874/fizzixs-electric-fields/
 
- Lucky Lake Amusement Park http://www.nedesigns.com/park/2996/lucky-lake-amusement-park/
 
- Mystic Mountain http://www.nedesigns.com/park/2967/mystic-mountain/
 
- Clearfield Woods http://www.nedesigns.com/park/3065/clearfield-woods/

Fizzix's Electric Fields and Lucky Lake Amusement park are actually based on rct2 scenarios (Electric land and build your own Six Flags Belgium) so those would probably be very interesting to have in the game. i'd love to see an extra tab in the scenario list as well consisting of user made parks if that's possible

**Comment by gijsdaboss** [comment]
okay so i got the permission for Tussauds Magical Kingdom, Märchen Paradies, Fizzix's Electric Fields and Mystic mountain as of now. i have 5dave's permission for floyd's family farm as well but it has a custom object and uses custom pathing and i don't really want to touch up the park too much.

http://i.imgur.com/xE55Vzd.png

so that only leaves us waiting for faas and csw for Lucky Lake Amusement Park and Clearfield Woods

**Comment by gijsdaboss** [comment]
alright new park i found. this one is probably one of my favorites yet

http://www.nedesigns.com/park/2545/banana-valley/

**Comment by IntelOrca** [comment]
Tussauds Magical Kingdom and Fizzix's Electric Fields unfortunately also use custom objects.

Märchen Paradies and Mystic Mountain however are ok!

**Comment by kevinburke** [comment]
you probably want a screenshot of a particular part of the park too, not
just the whole thing


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by IntelOrca** [comment]
@kevinburke I will try and craft a sequence through all the parks around areas in a similar fashion to RCT1.

**Comment by IntelOrca** [comment]
banana-valley uses two custom objects, XXWLWF02.DAT and XXWLWF03.DAT

**Comment by gijsdaboss** [comment]
thanks for rooting out the custom objects, i'll try to see if they have any major impact on the look of the park. if not then i'll post a new download without the objects. anyways it turns out that a park which i thought had custom path objects infact doesn't, so that means i can put it in here.

anyways Inselfieber http://www.nedesigns.com/park/2868/inselfieber/

and i got a message from faas stating that it's alright to use Lucky Lake Amusement Park

http://i.imgur.com/G9wIKvV.png

**Comment by IntelOrca** [comment]
When I load inselfieber in OpenRCT2, three rides instantly crash.

**Comment by gijsdaboss** [comment]
that's strange, i'll look into it tomorrow

also i made a version of Banana Valley without the custom objects, should be fine. i'll upload that tomorrow

**Comment by ipatix** [comment]
I have a question related to the title parks. Which map size should the have? I'm considering using a custom map I made some time ago for multiple perspectives but its size is 256x256 and I'm not sure if that's gonna make things more laggy or loading times longer.

**Comment by IntelOrca** [comment]
@ipatix, no loading times is mostly based on the number of types of objects used and lag is mostly based on how much there is to draw at once on the screen.

**Comment by Gammadivided** [comment]
Millennium Castle it up, bro.
http://www.mediafire.com/download/ax7u0do68bqdm8l/Millenium%2520Castle.SV6

![image](https://cloud.githubusercontent.com/assets/11410845/6649291/948681de-c9c5-11e4-9b11-8c41125ad089.png)

**Comment by PFCKrutonium** [comment]
Well that makes my Castle look shit...

**Comment by gijsdaboss** [comment]
alright we have CSW's and Jonny93's permission to use Clearfield Woods and Inselfieber

http://i.imgur.com/dUWrMyh.png

and here should be an updated version of Banana Valley without those 2 objects

http://www.mediafire.com/download/ackzid5tsy78zc9/Banana+Valley+Amusement+Park+by+ride6.SV6

**Comment by PFCKrutonium** [comment]
@IntelOrca Do you still need more parks?

**Comment by youssefdetovernickr** [comment]
I just want a park that's empty with 0 people, just like the first level of rct1

**Comment by RobertWHurst** [comment]
Checkout a my park, Gamond Forrest. I made it years ago, but You guys might like it. I put a ton of hours into it, with I high attention to detail.
[Gammond Forrest.sv6](https://drive.google.com/open?id=0B3Td5V_Lk8JrWks5M0J2ejB5MnM&authuser=0)
[Gallery](http://imgur.com/a/bR93b)

**Comment by Gammadivided** [comment]
Looks like you had a lot of fun making the park! Looks a lot like those Six Flags scenarios.

**Comment by RobertWHurst** [comment]
@Gammadivided Thanks, yeah. I definitely put a lot of hours into it.

**Comment by Christipher** [comment]
I have two parks that I am sharing - one of which has one of my best works within it (and two irremovable rides)
Starting with the blank one:
Riverview Park - <a href=http://www.filedropper.com/riverviewpark><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >upload files online</a></div>
Fun at the Beach: <a href=http://www.filedropper.com/funatthebeach><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >online backup storage</a></div>

Both of the above scenarios are difficult and require ridiculous skills to pass... but they are possible.
