### ISSUE TITLE
Ride Ad Campaign Finish Glitch

### ISSUE THREAD

**Issue by jacon500** [IntelOrca/OpenRCT2#909]
Whenever an ad campaign for a ride finishes, it often doesn't display the name of the advertised ride. Instead, it shows either no name or a name of some other structure (ride/stall) in the park.

**Comment by PFCKrutonium** [comment]
![screenshot 20](https://cloud.githubusercontent.com/assets/3945538/6587932/2ad54808-c761-11e4-8ff4-723b646fc030.png)
![screenshot 21](https://cloud.githubusercontent.com/assets/3945538/6587933/2ad73456-c761-11e4-957f-8152960bb64b.png)

Confirmed, though I just got messages with the name missing.

**Comment by LaPingvino** [comment]
Confirmed this bug: had free tickets for a ride (with a custom name), told it was finished for the drink stall (with a custom name)
