### ISSUE TITLE
Compiling on Linux breaks money display

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#912]
When the game is compiled on my Linux system using the build script provided it will show nearly every amount of money as 0.

Ubuntu 14.10, amd64.

**Comment by PFCKrutonium** [comment]
Confirmed on Kali Linux - Except it is the other way around for me. Initial Loan $1,280,000.00...

Loan increases by $256,000, and peeps are paying by the same multiple. All the money seems to be multiplied.

$0.10 = $25

**Comment by PFCKrutonium** [comment]
204,030.30 Euro = 52,231,756 Dollars = 0.00 Yen (Wrong Currency Symbol)

**Comment by PFCKrutonium** [comment]
![scr1](https://cloud.githubusercontent.com/assets/3945538/6649127/e06123a4-c9b9-11e4-90a7-7b876372d277.png)
![scr2](https://cloud.githubusercontent.com/assets/3945538/6649126/e05fcb30-c9b9-11e4-88b4-bfffe29408e7.png)
![scr3](https://cloud.githubusercontent.com/assets/3945538/6649129/e0775f8e-c9b9-11e4-9d85-e65d04cb3962.png)
![scr4](https://cloud.githubusercontent.com/assets/3945538/6649131/e0780efc-c9b9-11e4-87f9-7caae3cb55d3.png)
![scr5](https://cloud.githubusercontent.com/assets/3945538/6649128/e076f5ee-c9b9-11e4-88a9-be2b927d7b48.png)
![scr6](https://cloud.githubusercontent.com/assets/3945538/6649132/e078b316-c9b9-11e4-8a5b-b76cb3978848.png)
![scr7](https://cloud.githubusercontent.com/assets/3945538/6649133/e0838d22-c9b9-11e4-9719-ce1f35895b17.png)
![scr8](https://cloud.githubusercontent.com/assets/3945538/6649130/e077a016-c9b9-11e4-8e9a-b73e6ad4bada.png)
![scr9](https://cloud.githubusercontent.com/assets/3945538/6649135/e087be7e-c9b9-11e4-97e1-3e7a98dcb43b.png)
![scr10](https://cloud.githubusercontent.com/assets/3945538/6649134/e0879d72-c9b9-11e4-831a-4269f85f07cf.png)

**Comment by Gymnasiast** [comment]
Thanks for investigating and posting those screenshots. Switching between currencies like you did in the screenshots produces the same results for me as in the screenshots.
