### ISSUE TITLE
Request: Please, bring back the RCT1 Steel/Looping Coaster train type as an alternative

### ISSUE THREAD

**Issue by Patrik356b** [IntelOrca/OpenRCT2#917]
![steelrollercoaster](https://cloud.githubusercontent.com/assets/2000703/6657933/c3dcb56c-cb59-11e4-9118-2839ed370023.png)

Red/green is areas you can change color of. I'd appreciate this very much.

**Comment by Gymnasiast** [comment]
Actually, this is already possible in vanilla RCT2, by extracting the sprites from RCT1 (I believe they reside in csg1.dat) and creating a new vehicle for the Looping Roller Coaster, using RideMaker for example. But it is a bit labour-intensive.

**Comment by IntelOrca** [comment]
As @Gymnasiast said, this is actually not related to game code. Vehicles are separate object files that you can create.

**Comment by PFCKrutonium** [comment]
http://ae.rctspace.com/ <- Has a Guide for making rides and stuff.

**Comment by Patrik356b** [comment]
I'll try that later then, but my game has been having issues not starting lately

**Comment by Gymnasiast** [comment]
Do note that you still need a way to extract the images from the RCT1 files.
