### ISSUE TITLE
Negative age for rides with a build date in the future

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#921]
RCT2 allows rides with ages up to 8192 years (actually 65536 months), overflowing to 0 (brand new). However, OpenRCT2 seems to use a signed number, which makes rides that are 8180 years old show up as being -12 years old: (ignore the window colour please)

![scr19](https://cloud.githubusercontent.com/assets/1478678/6676974/3cbb9796-cc2c-11e4-9d6a-238241ff9120.png)

**Comment by IntelOrca** [comment]
Should probably stop the overflow from happening too.

**Comment by Vijfhoek** [comment]
What about using floating points for this?

**Comment by Gymnasiast** [comment]
@IntelOrca: Is that possible? I'd imagine the age is stored in a 16 bit unsigned integer in the SV6.

**Comment by Vijfhoek** [comment]
A rather radical solution to that would be creating a new save format and allowing people to import/export SV6 saves? I don't know if an issue has been created for that, I haven't followed this project for quite some time.

**Comment by IntelOrca** [comment]
I mean prevent overflow, by not incrementing the age once its reached its highest possible value.
@Vijfhoek RCT2 never uses floating point types, so I prefer to avoid using them. SV6 files will always be loadable, however as soon as we add new features that are saved - we will have to save in a new format that can't be loaded in vanilla RCT2.

**Comment by Gymnasiast** [comment]
I have to add that ride ages like 8180 are usually the result of resetting the date using a trainer, and isn't actually a limit that the normal user would encounter. (And which makes an age of -12 a bit true ;).
 )

**Comment by Gymnasiast** [comment]
Adjusted title since problem isn't a very old age, but a broken build date.
