### ISSUE TITLE
Peeps won't interact with shops or rides

### ISSUE THREAD

**Issue by Enzemo** [IntelOrca/OpenRCT2#922]
Hey,

So for some reason none of the peeps will interact with any of my rides or shops. I'm not sure why. I get some checksum errors on a number of objects, but I don't see why that would affect my peeps using normal rides that have loaded?

![scr6](https://cloud.githubusercontent.com/assets/11069930/6677053/804a2cdc-cc24-11e4-9125-a896ac8407f6.png)

Here's my game save and the original scenario, download and rename to .sv6
https://cloud.githubusercontent.com/assets/11069930/6677017/4233a9b4-cc24-11e4-9a33-a73c2213980b.png

https://cloud.githubusercontent.com/assets/11069930/6677037/6679e1ee-cc24-11e4-832e-0b4f716b50fe.png
Same for this, just .sc6

**Comment by duncanspumpkin** [comment]
Was this scenario made in OpenRCT2?

**Comment by Gymnasiast** [comment]
Did you switch from money to no money? I recall there being issues with that, since the prices are not reset though new guests arrive with no money, causing weird issues like this.

**Comment by Enzemo** [comment]
Yes, it was made within OpenRCT and no, I didn't change from money to no money - that was set in the scenario editor. 

Do you need the files from me, duncan?

**Comment by duncanspumpkin** [comment]
I could spend a while searching for them on nedesign but if you could zip them up that would be much quicker. I wont be able to look at it for a day or 2 though.

**Comment by Enzemo** [comment]
No problem - thank you for your help. It's likely my own fault, but hopefully it can highlight some issues with custom object compatibility.

None of these objects are showing ingame btw; needless to say I haven't placed any of them in my attached savegame. I included the savegame and scenario too - they are identical to my above. 

http://www.filedropper.com/enzemossandboxbugged

Also I got this upon launching OpenRCT, might be related, no idea:

>Starting OpenRCT2 v0.2.0-develop-058f10845f0c160eea619ede25f6a3e0dcfeafcc b494,
OpenRCT2.com
  Windows (x86)
  Mar 18 2015 00:52:27

>Time: 2015/03/18 01:32:47
>ERROR[..\src\object.c:96 (object_load_file)]: Object Load failed due to checksum
 failure.
>ERROR[..\src\object_list.c:621 (install_object_entry)]: Object Load File failed.
 Potentially corrupt file: HATS
>ERROR[..\src\object.c:96 (object_load_file)]: Object Load failed due to checksum
 failure.
>ERROR[..\src\object_list.c:621 (install_object_entry)]: Object Load File failed.
> Potentially corrupt file: HATS

**Comment by duncanspumpkin** [comment]
Will take a look at this tonight. Those warnings happen because of corrupt object files it shouldn't effect peeps useing the rides as most of the corrupt warnings are just because someone incorrectly calculated the checksum. I have a strong feeling there must be an object generation tool that someone has made a mistake in that is generating these incorrect checksums.

**Comment by duncanspumpkin** [comment]
Found the source of the issues. Its caused by the intense rides flag. At present its incorrect in the scenario editor. I will make a patch that fixes it but sadly this save is toast and so is the scenario save.

**Comment by Enzemo** [comment]
Thank you very much, it's much appreciated. Glad that you were able to fix it for the future :)
