### ISSUE TITLE
Some ride entrance banners do not scroll properly

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#931]
It's hard to tell from the screenshot, but the banner of the Junior RollerCoaster shows garbled text most of the time. It looks like the area isn't properly invalidated. It also affects one other ride in the save, and also one of two in another save.

![scr38](https://cloud.githubusercontent.com/assets/1478678/6740562/23727122-ce81-11e4-96ce-e334247b2b16.png)

**Comment by IntelOrca** [comment]
Could be related to cd16af0f60a607b9cef633566d96ce2c5b32b170, can you check if this happens before this commit?

**Comment by Gymnasiast** [comment]
It also happens in build 496, released 18 March, 14:16 - before cd16af0f60a607b9cef633566d96ce2c5b32b170.

**Comment by Gericom** [comment]
It's this related to localisation? (aka. wrong string length)

**Comment by Gymnasiast** [comment]
I don't think so. It happens on two rides in this park: one with a default name, but also one with a custom name.

**Comment by LaPingvino** [comment]
I see this as well (Linux, under wine, might be related...) and it seems to happen or not happen depending on how the screen is shifted...

**Comment by duncanspumpkin** [comment]
Can you recheck this and see if it occurs still I have a feeling the recent fixes to map animation should have stopped this bug.

**Comment by Gymnasiast** [comment]
It seems to be solved. The two saved games I got the issue with are fixed by moving entrances, so I'll just close it. Thanks!
