### ISSUE TITLE
Balloon Animation Glitched

### ISSUE THREAD

**Issue by PFCKrutonium** [IntelOrca/OpenRCT2#938]
It seems to be rapidly switching between two parts of a ride entrance and the balloon popping animation.
![scr1](https://cloud.githubusercontent.com/assets/3945538/6759130/2137f95c-cf14-11e4-8f99-c9c69cd2e7ce.png)

https://www.dropbox.com/s/ywlpptymjohq386/Crazy%20Castle_Glitch.sv6?dl=1

**Comment by IntelOrca** [comment]
@PFCKrutonium Can you let me know if this still happens, thanks.

**Comment by PFCKrutonium** [comment]
@IntelOrca It seems to have been corrected.
