### ISSUE TITLE
Bugged scenery after saving track design

### ISSUE THREAD

**Issue by ipatix** [IntelOrca/OpenRCT2#964]
Just found another issue that sometimes occurs when saving track designs with scenery.

This is the original track design:
![scr6](https://cloud.githubusercontent.com/assets/8502545/6838271/b0d125f2-d356-11e4-96db-638857e46887.png)

This is how it saves it:
![scr5](https://cloud.githubusercontent.com/assets/8502545/6838210/00fe4362-d356-11e4-9031-7b1add2a891c.png)

For some reason the scenery will kind of shift diagonally.

PS: I ran into another problem (probably not a bug) when saving the original. I can't select all of the scenery from the design because I'd select "too much" otherwise. Would there be a way to bypass that limit without breaking anything (incase this would prevent something like oversized files)?

**Comment by duncanspumpkin** [comment]
Limit for now can't be bypassed without making a new type of track format. I'm not too sure if we can accommodate a new track format just yet though. I think we still have one or two functions that would break if that was changed.

As for the bug can you provide a save with the track all ready for saving and a copy of the track with the bug. Is it displayed incorrectly in the track preview window?
