### ISSUE TITLE
Peep ride issues

### ISSUE THREAD

**Issue by duncanspumpkin** [IntelOrca/OpenRCT2#965]
Can everyone who has encountered issues with the latest build in terms of peeps and rides put information about them in here.

So far known issues are:
peeps are walking along the edges of the rapids ride
https://files.gitter.im/IntelOrca/OpenRCT2/VpPj/blob

**Comment by Gymnasiast** [comment]
People walking in the air, beyond the edge of the platform - might be the same as the rapids bug:
https://files.gitter.im/IntelOrca/OpenRCT2/J9hV/thumb/SCR52.png

**Comment by duncanspumpkin** [comment]
Issue with peeps getting on Enterprise ride.
