### ISSUE TITLE
RCT1 Mazes not imported correctly

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#974]
Using maze designs from RCT1 (TD4 files) has two issues:
- There are no hedges, just plain ground
- The entrance and exit building are swapped

![scr55](https://cloud.githubusercontent.com/assets/1478678/6882713/5d898f70-d58f-11e4-9dda-e50c2c3d38e2.png)

**Comment by duncanspumpkin** [comment]
Can you try deleting the track file and reinstalling the file?

**Comment by Gymnasiast** [comment]
The problem seems to be solved without deleting; do I still need to delete the file?

**Comment by duncanspumpkin** [comment]
No just suggesting ideas. If its fixed then I guess thats good. Not sure what caused it.
