### ISSUE TITLE
Mechanic that's fixing a ride has a status of 'Heading to [ride] for an inspection'

### ISSUE THREAD

**Issue by Gymnasiast** [IntelOrca/OpenRCT2#984]
![scr58](https://cloud.githubusercontent.com/assets/1478678/6902308/44229b64-d713-11e4-9668-d868298bf8f9.png)

**Comment by runelaenen** [comment]
I can't seem to reproduce the bug, nor can I find any reason it shouldn't work...

**Comment by Gymnasiast** [comment]
@runelaenen: Doesn't mean there isn't a bug. -,-  Have you actually looked at #977 and #983?

**Comment by runelaenen** [comment]
@Gymnasiast I know, I'm just stating what I'm finding

**Comment by Gymnasiast** [comment]
Seems to be fixed by #992.
