### ISSUE TITLE
Very happy guests getting angry after visiting the toilet

### ISSUE THREAD

**Issue by Parkmanager** [IntelOrca/OpenRCT2#986]
I followed some very happy guests (~90%+ happiness) to the toilet and found this bug.
Other guests with lower happiness are not affected.
After some testing i found out that this bug was introduced in build 520.

**Comment by Gymnasiast** [comment]
Sounds like a parameters overflowing.

**Comment by Gymnasiast** [comment]
Row 2450 in peep.c sets the happiness_growth_rate to 0xFF if that's lower than happiness_growth_rate+30. happiness_growth_rate is a signed 8 bit integer, which has a maximum value of 0x7F if I'm not mistaken, so 0xFF will make it negative. (Am I correct?)

**Comment by duncanspumpkin** [comment]
I don't think happiness growth rate should be signed. Will require some checking though before making a change.

**Comment by Saren-Arterius** [comment]
I think it's time to clean your toilets...

**Comment by Villacaleb** [comment]
This is a really funny bug.
