### ISSUE TITLE
Mechanics do Inspections before Breakdowns

### ISSUE THREAD

**Issue by jacon500** [IntelOrca/OpenRCT2#991]
Whenever a ride is broken down, and there is another ride that is at or past the scheduled inspection time, the mechanic will almost always go to the inspection rather than fix the broken ride.
![scr5](https://cloud.githubusercontent.com/assets/10506571/6956200/032f2ab6-d8b0-11e4-8457-0c6d6872bf6e.png)

**Comment by Parkmanager** [comment]
Looks like fixed issue #977. Are you playing with the actual build? (b545 from openrct2.com/download)

**Comment by jacon500** [comment]
Yes, I just downloaded it yesterday and was playing with that version.

On Wednesday, April 1, 2015, Tom <notifications@github.com> wrote:

> Looks like fixed issue #977
> <https://github.com/IntelOrca/OpenRCT2/issues/977>. Are you playing with
> the actual build? (b545 from openrct2.com/download)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntelOrca/OpenRCT2/issues/991#issuecomment-88708737>.
>


-- 
Jacon
jacon500@gmail.com

**Comment by duncanspumpkin** [comment]
okay ill take a look again. This bug is a bit annoying since its hard to test.

**Comment by duncanspumpkin** [comment]
I have a strong feeling i know why its still not working.
