### ISSUE TITLE
Ferris wheel rotation direction configuration is incorrect

### ISSUE THREAD

**Issue by Padankadank** [IntelOrca/OpenRCT2#994]
The Ferris Wheel "Forward Rotation" ride option has the ride actually spin backwards.

**Comment by duncanspumpkin** [comment]
I take it this was correct in the original game?

**Comment by Gymnasiast** [comment]
Works as intended in RCT2 and OpenRCT2. The forward or backward rotation is from the rider's perspective - when they get into the ride, they go forward first if the ride is set to Forward rotation.
